reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/ProjectModelToApplicationIndexMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/CreateSourceReportRuleProvider.java
reporting/impl/src/main/resources/reports/templates/include/navbar.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl

https://issues.jboss.org/browse/WINDUP-447

WINDUP-447: NPE halts Windup execution

---

dist/pom.xml

An alternative implementation of https://github.com/windup/windup/pull/469.
Basically this makes the dist depend on the bom, because it appears that the addon-installs themselves depend on it. I think this also fixes the double build issue on release.

WINDUP-510: Fix build order

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/JavaASTProcessor.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/data/JavaClassReference.java
java-ast/tests/src/test/java/org/jboss/windup/ast/java/JavaASTProcessorTest.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbAnnotationsRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClass.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClassBuilderLineMatch.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/JavaTypeReferenceModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/service/TypeReferenceService.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/service/TypeReferenceServiceTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassSourceMatchTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassXmlRulesTest.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/java/JavaClassTestFile1.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/java/JavaClassTestFile2.java

This PR adds new attribute to JavaClass, so now we will be able to query the raw line of the file like so:
```
JavaClass.references({*}.MySimpleClass.mySimpleMethod(java.lang.String)).matchesSource("{*}{line}").at(TypeReferenceLocation.METHOD_CALL).... where("line").matches(".methodCall(new .*")
```
This condition distinguish the hard-coded string inside the mySimpleMethod call.

 	MIGR-226: Improve the capabilities of the Java AST source analyzer

---

graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java

I've played with the settings over weekend and this gave me about 7% performance improvement on HDD.
See http://s3.thinkaurelius.com/docs/titan/current/bulk-loading.html
The default is 1024.

Increase Titan's storage.buffer-size = 4096

---

graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/DoctypeMetaModel.java

This speeds Windup up by 200 %. It fixes the indexed property name.
The real change we should do (IMO) is WINDUP-532.

WINDUP-529 Performance issue: Query requires iterating over all vertices [(ClassificationModel:classification = ...)]

---

rules-java/api/pom.xml

It might have something in common with WINDUP-557.

WINDUP-557? Upgrade roaster-jdt 2.12 - sync with Forge.

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/DecompilerUtil.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/FernflowerDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/ProcyonDecompilerOperation.java
rules-java/tests/src/test/resources/classmetadatatest/sampleclasses/com/rhc/booking/services/EventServer.java
rules-java/tests/src/test/resources/classmetadatatest/sampleclasses/com/rhc/booking/services/impl/EventServerImpl.java

https://issues.jboss.org/browse/WINDUP-685

WINDUP-685: Inappropriate output directory selection in some cases

---

bom/pom.xml
config-groovy/tests/pom.xml
config-xml/tests/pom.xml
config/tests/pom.xml
exec/tests/pom.xml
graph/tests/pom.xml
java-ast/tests/pom.xml
pom.xml
reporting/tests/pom.xml
rexster/tests/pom.xml
rexster/tests/src/test/java/org/jboss/windup/graph/rexster/test/debug/RexsterDefaultDeploymentDebugTest.java
rexster/tests/src/test/java/org/jboss/windup/graph/rexster/test/debug/RexsterDefaultDeploymentNoDebugTest.java
rules-base/tests/pom.xml
rules-java-archives/tests/pom.xml
rules-java-ee/tests/pom.xml
rules-java-project/tests/pom.xml
rules-java/addon/pom.xml
rules-java/tests/pom.xml
rules-tattletale/addon/pom.xml
rules-tattletale/tests/pom.xml
rules-xml/tests/pom.xml
test-util/pom.xml
tests/pom.xml
tooling/tests/pom.xml
ui/tests/pom.xml
windup-test-harness/pom.xml
windup-test-harness/src/main/java/org/jboss/windup/arquillian/WindupFurnaceAddonDeploymentEnhancer.java
windup-test-harness/src/main/resources/META-INF/services/org.jboss.forge.arquillian.spi.AddonDeploymentScenarioEnhancer

From now on, rexster is deployed by default everytime you debug within windup.

WINDUP-670: Make Rexster more convenient to use

---

graph/impl/src/main/java/org/jboss/windup/graph/MapInAdjacentPropertiesHandler.java
pom.xml
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintEffort.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintLink.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintSeverity.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintText.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/ClassificationTags.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/GetTagsFromFileClassificationsAndHints.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/ClassificationHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/HintHandler.java
reporting/tests/src/test/java/org/jboss/windup/reporting/handlers/HintHandlerTest.java
reporting/tests/src/test/resources/handler/hint.windup.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/FindUnboundJavaReferencesRuleProvider.java
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/tests/src/test/java/org/jboss/windup/rules/java/ignore/JavaIgnoreRegexesTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java
tests/src/test/xml/XmlExample.windup.xml

For now, it is storing the tags in @SetInProperties.
What's new: 
* tags added to InlineHint and Classification;
* <tag> handled for <hint> and <classification>
* Tags appear in the report next to TechnologyTags for the files
* Test added for those

Handle tags windup 679

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/TargetOption.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/BatchASTProcessor.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/config/EnableClassNotFoundAnalysisOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/DecompilerUtil.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/FernflowerDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/WindupJavaConfigurationModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/FindUnboundJavaReferencesRuleProvider.java
rules-java/impl/src/main/java/org/jboss/windup/rules/apps/java/config/CopyJavaConfigToGraphRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassBindingStatusTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassWithoutHintTest.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupCommandRuleFilteringTest.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupCommandTest.java
utils/src/main/java/org/jboss/windup/util/PathUtil.java

This also makes "target" a required parameter.

Fixed an issue with path selection during decompilation. Also, made the unbound references scanning functionality optional

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/data/TypeReferenceLocation.java

(14:08:08) mbriskar: ozizka, it will. implements/extends is transitive
(14:08:28) mbriskar: ozizka, even method_call probably is transitive

WINDUP-723 Improve TypeReferenceLocation javadoc

---

config/api/src/main/java/org/jboss/windup/config/operation/Commit.java
config/api/src/main/java/org/jboss/windup/config/operation/Iteration.java
config/api/src/main/java/org/jboss/windup/config/operation/IterationProgress.java
config/api/src/main/java/org/jboss/windup/config/operation/OperationUtil.java
config/tests/src/test/java/org/jboss/windup/config/iteration/IterationAutomicCommitTest.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverAllSpecifiedTest.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationServiceCache.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/IndexJavaClassFilesRuleProvider.java

This still needs:
1. Code cleanup (additional comments)
2. A Unit test
3. A full run of the Windup unit tests
This also adds implicit periodic commits and progress monitoring to any Iteration that does not already have them enabled.

WINDUP-762: Windup is exceptionally slow to process applications in which a single rule attaches a large number of classifications

---

reporting/impl/src/main/resources/reports/templates/classloader.ftl
reporting/impl/src/main/resources/reports/templates/embedded.ftl
reporting/impl/src/main/resources/reports/templates/include/userfeedback.ftl
reporting/impl/src/main/resources/reports/templates/index.ftl
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/server-resources.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
reporting/impl/src/main/resources/reports/templates/windupfreemarkerfunctions.ftl

This is a fix for having more XHTML compliant reports.
With this fix it is for example possible to process and merge the summary files using xmllint.

Fixing (X)HTML markup

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OutputPathOption.java
exec/tests/src/test/java/org/jboss/windup/exec/test/OutputPathOptionTest.java

https://issues.jboss.org/browse/WINDUP-782

WINDUP-782: Specifying the same file as both an input and an output results in the input file being destroyed

---

reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl

not-executed makes people think that the rule was not executed at all, including the condition.
16:44:33) jsightler: ozizka: Maybe "not-matched" would be better than "not-performed"?
(16:44:54) jsightler: To me, not-performed and not-executed are essentially synonymous 
(16:45:21) rruss: +1
(16:45:46) ozizka-FN: maybe
(16:46:00) marekn: jsightler: +1
(16:46:05) ozizka-FN: but it's right next to  the rule sounding like "when( ... ) perform( ... )
(16:46:29) ozizka-FN: And the other would be "matched"?
(16:46:51) ozizka-FN: I am okay with not-matched and performed
(16:47:00) jsightler: Yeah, I get your point. Maybe there is a better term?

Change misleading "not-executed" to "not-performed"

---

reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/RenderRuleLinkDirective.java
reporting/impl/src/main/resources/reports/resources/css/windup-source.css
reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/templates/classloader.ftl
reporting/impl/src/main/resources/reports/templates/index.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/server-resources.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
reporting/impl/src/main/resources/reports/templates/windupfreemarkerfunctions.ftl
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
rules-java-ee/addon/src/main/resources/reports/templates/hibernate.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jbpm.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl
rules-java/api/src/main/resources/reports/templates/about_windup.ftl
rules-java/api/src/main/resources/reports/templates/compatible_files.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/api/src/main/resources/reports/templates/static_ip_addresses.ftl

    WINDUP-796  Source Report style should be consistent with other reports

---

rules-tattletale/addon/src/main/java/org/jboss/windup/rules/apps/tattletale/TattletaleRuleProvider.java

Puts a config .properties file and points tattletale to it.
Skips the .png which takes long but not the .dot which someone might then want.
I'd like to add a condition - IF the app is big (~over 50 packages), THEN skip it.

WINDUP-795 Skip Tattletale's generation of the .png file

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/JspFileMappingRuleProvider.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/DiscoverXmlFilesRuleProvider.java

This is important to get JSF files into reports. XML rules will continue in windup-rulesets

WINDUP-691 register xhtml/jsf file mapping as XMLFileModel

---

config/api/src/main/java/org/jboss/windup/config/query/Query.java

The question is if we even need this, since that filtering functionality is never used with query.

Iterables.filter() instead of List filtering

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java

All the field information that remains after the operation runs will stay stored throughout the whole windup execution. This is a simple fix and may have bigger impact, however the biggest problem still remains the graph database. The first point in the https://gist.github.com/mbriskar/3f2e4f502e68ad614fdd documentation of issue

Fighting the Out of memory exception 1.commit

---

graph/api/src/main/java/org/jboss/windup/graph/Indexed.java
graph/api/src/main/java/org/jboss/windup/graph/model/ProjectModel.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HasHint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/GetTagsFromFileClassificationsAndHints.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ApplicationReportModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/EffortReportModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/TagSetModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/TaggableModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/rules/AttachApplicationReportsToIndexRuleProvider.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/InlineHintService.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/TagSetService.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/CreateMigrationIssuesReportRuleProvider.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/rendering/RenderReportRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/service/TypeReferenceService.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/service/TypeReferenceServiceTest.java

The main change is that EffortReportModel now does a range index on effort.
The effort calculation queries now use this and run much quicker.
(also, hint and classification operations now show their timings in the detailed_stats.csv)

Reporting speed fixes

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/ApplicationReportModel.java

In some cases getXYZ() is never called and therefore no reason to have setXYZ()

Clean unused ReportModel properties

---

reporting/impl/src/main/resources/reports/templates/index.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl

This is an alternative to https://github.com/windup/windup/pull/798 with just titles for technology tags *without showing popup technology tag label legend*

WINDUP-856 added titles for technology tags in reports

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/XmlFile.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/XmlFileNamespace.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/XmlFileParameterMatchCache.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XmlFileLongXpathTest.java

This may be a rather complicated issue.
In the xpath, we generate multiple startFrame(index...) methods that register Maps in the cache. However, if the xpath is long, not all of the startFrame() are executed that means not all of the numbers are registered.

WINDUPRULE-109: Long Xpaths suffered from not executed parts

---

rules-java/api/src/main/resources/reports/templates/report_index.ftl

HTML 5 != XHTML. Throws warnings in strict mode.

Fix div close

---

pom.xml
rules-tattletale/tests/pom.xml
test-files/pom.xml

This will serve for tests outside of the windup/windup repo (e.g. windup-maven-plugin).
Result:
--- maven-install-plugin:2.5.2:install (default-install) @ windup-test-files ---
No primary artifact to install, installing attached artifacts instead.
Installing /home/ondra/work/Migration/Windup/test-files/pom.xml to /home/ondra/.m2/repository/org/jboss/windup/tests/windup-test-files/2.5.0-SNAPSHOT/windup-test-files-2.5.0-SNAPSHOT.pom
Installing /home/ondra/work/Migration/Windup/test-files/jee-example-app-1.0.0.ear to /home/ondra/.m2/repository/org/jboss/windup/tests/windup-test-files/2.5.0-SNAPSHOT/windup-test-files-2.5.0-SNAPSHOT-jeeapp.ear

WINDUP-933  Create a test resources artifact containing the test jee-app

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/SpringBeanModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateSpringBeanReportRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverSpringConfigurationFilesRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/SpringBeanService.java

Note that this PR does not contain a test. Actually, I'm not quite sure how to write such a test yet. But I will try to do my best if it's required ;-)

WINDUP-952 Multi-application support for Spring bean report

---

utils/pom.xml

Version 4.0 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/

Upgrade Apache Commons Collections to v4.1

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/DiscoverXmlFilesRuleProvider.java

It clutters the output too much.

Push the XML parse error stacktrace to FINE level.

---

graph/api/src/main/java/org/jboss/windup/graph/GraphContext.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java

and few others. Reduces boilerplate a bit in the Java-based rules.

    WINDUP-978 Convenience: ...Model m = GraphContext#create(Class<..Model> type);

---

reporting/impl/src/main/resources/reports/templates/application_list.ftl

In the title and help text for other reports: all words capitalized in title, word "report" not capitalized in help text

make app list title/text style consistent with other reports

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java

This may sound trivial, but it will reduce the size of the reports .html and .js by few megabytes.
The values need to be trimmed right when created, not in the reports, because somewhere they are printed through things like ObjectWrapper.

    WINDUP-987 Trim the text of titles, hints and classifications

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/ResolveServerResourceLinksRuleProvider.java

AFAICT link originally pointed to 18.8. Configuration (for Messaging) -- at some point 23.2 Configuration (for Hibernate Search) was added, and whatever generates the documentation html effectively changed sect-Configuration.html from pointing at 18.8 to pointing at 23.2. (Not a friendly behavior...)

MIGRFEED-17 fix link to JMS configuration

---

rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/ValidateXmlFilesRuleProvider.java

https://issues.jboss.org/browse/WINDUP-997

WINDUP-997: spring-mvc.xml as invalid by 'XML File is not valid' rule

---

rules-java/api/src/main/resources/reports/templates/static_ip_addresses.ftl
test-util/src/main/java/org/jboss/windup/testutil/html/TestStaticIPReportUtil.java

As pointed out by Marc. Not renaming any files/imports/etc, just fixing text.
Not confident that this catches every remaining instance of "static IP" text in Windup. The word "static" is used a lot in code in ways that makes find+replace hard. But this PR includes all of the ones I've seen in my reports.

WINDUP-1076: update remaining references to "static IP" to "hard-coded IP"

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJavaIgnoredFilesReportRuleProvider.java

Removing the link entirely here rather than pointing it to somewhere else. Doesn't seem like our GH wiki is a stable enough place to point links at, and probably not worth the maintenance burden of keeping links from Windup output to RH Windup documentation in-sync unless we're going to do it in enough places to get significant value out of it.

WINDUP-1083: Remove dead doc link in Ignored Files report

---

reporting/api/src/main/java/org/jboss/windup/reporting/rules/CreateApplicationListReportRuleProvider.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl

(I see no ID to refer to)
https://docs.google.com/document/d/1nnsmOu8INH_jxcyAYyry1TTtf47AMYE8BR9OjrGi3jI/edit?ts=575842d0
This is based on the #5 version from the other app list design PR #975 (== has shared commits)
2.6 App list tweaks based on discussion on 20160616:
Start with the latest version without the bubble (version #5 of the 6 Ondra shared)
Shared libs story point number feels a little too prominent
We need to communicate this number but it doesn't need to be so huge
Possible options:
✔ Replace the large shared-libs number with two smaller shared + unique numbers
Remove the extra column, and display the shared+unique numbers directly underneath the total story points number (possibly using the stacked-progress-bar style of visualization we talked about)
✔ There is quite a lot …

App list design3 feedback2

---

pom.xml

This is direct suggestion to maven that parent is remote not local file
> Maven looks for the parent POM first in this location on the filesystem, then the local repository, and lastly in the remote repo. 
We skip by this change the filesystem. Not a problem but we can see this plenty of warnings on our CI jobs, when windup is checked out with other repos on filesystem.

tell maven it is always remote parent pom

---

bootstrap/pom.xml

https://issues.jboss.org/browse/WINDUP-1200
and cleaned a bit compile scopes which are by default COMPILE so not required to be specified there.

WINDUP-1200: rolled back excluded rewrite dependency in bootstrap

---

config/api/src/main/java/org/jboss/windup/config/AbstractRuleLifecycleListener.java
config/api/src/main/java/org/jboss/windup/config/GraphRewrite.java
config/api/src/main/java/org/jboss/windup/config/RuleLifecycleListener.java
config/api/src/main/java/org/jboss/windup/config/RuleSubset.java
config/api/src/main/java/org/jboss/windup/config/operation/Iteration.java
exec/api/src/main/java/org/jboss/windup/exec/CombinedWindupProgressMonitor.java
exec/api/src/main/java/org/jboss/windup/exec/WindupProgressMonitor.java
exec/impl/src/main/java/org/jboss/windup/exec/DefaultRuleLifecycleListener.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
exec/tests/src/test/java/org/jboss/windup/exec/test/SkippingReportsRenderingTest.java
exec/tests/src/test/java/org/jboss/windup/exec/test/TagsIncludeExcludeTest.java
graph/api/src/main/java/org/jboss/windup/graph/model/WindupExecutionModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/ruleexecution/RuleExecutionResultsListener.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureStopTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java
tooling/api/src/main/java/org/jboss/windup/tooling/ExecutionResults.java
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionBuilderImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionResultsImpl.java
utils/src/main/java/org/jboss/windup/util/exception/WindupStopException.java

This makes use of WindupProgressMonitor#isCancelled().
That is queried in DefaultRuleLifecycleListener
which is queried by RuleSubset. 
RuleSubset, on spoting stop request, stops the rules cycle and creates a WindupExecutionModel vertex.

T379 Make it possible to stop running Windup core execution

---

reporting/api/src/main/java/org/jboss/windup/reporting/TagUtil.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/ProblemSummaryService.java

I had issue with very non intuitive tag include/exclude in windup-web.
I added method which returns true if:
- tag is included or tag is not excluded
It checks if includeTags is not empty, if it is not, tag is included ONLY when it is in includeTags.
If includeTags is empty, tag is by default included, but is excluded, when it is in excludeTags.

Added different method for tag comparison.

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/weblogic/ResolveWebLogicEjbXmlRuleProvider.java

Set effort to 0 in clsf generated by ResolveWebLogicEjbXmlRuleProvider to avoid duplicating effort from weblogic-xml-descriptors-04000 hint.
Hint with effort was added after 2.7 in this commit: https://github.com/windup/windup-rulesets/commit/baf299554f86d834c9e9188d9d06477cc3ed08b6

Remove effort from WebLogic EJB XML clsf that has a hint with effort.

---

rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/EnhancedEntityResolver2.java
rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/ValidateXmlFilesRuleProvider.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/rules/ValidateXmlFilesRuleProviderWithInternetTest.java

This is still a little weird, as this creates some validation errors on poms and things like that. I really wonder if we should just skip this rule entirely in offline.

WINDUP-1298: Really don't make network calls in offline

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/ConsoleProgressMonitor.java
exec/impl/src/main/java/org/jboss/windup/exec/DefaultRuleLifecycleListener.java

1. pad the n-th message to be long as the (n-1)-th message to have every message clearly written without the final part of the previous one
2. print the n-th message with the "\r" carriage return to stay on the same line
3. println the next rule execution message with "\r" prefix to have the log clear with just all the rules executed

Console progress output on the same line

---

reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/MarkdownToHtmlMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/ToHtmlSerializerExtended.java
reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/RenderLinkDirective.java

- created `ToHtmlSerializerExtended` class to override `org.pegdown.ToHtmlSerializer.printLink(LinkRenderer.Rendering rendering)` method to always add the `target='_blank'` attribute to markdown defined links
- add `target='_blank'` attribute to links in hints in Migration Issues Report and Source Report (both in code snippet and in categories header) 
- add CSS directive to use Font Awesome (font file already in project)
- add external-link icon from Font Awesome after every link with `target='_blank'` attribute defined
You can see the result in next screenshots:
- Migration Issues Report
- Source Report (code snippet) 
- Source Report (categories header)
PS: source.ftl is highlighted all in red all around the line changes but `git diff` locally doesn't show all that changes. Maybe some …

T877 Links to articles should open in a new tab

---

graph/api/src/main/java/org/jboss/windup/graph/model/ProjectModel.java
graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetProblemSummariesMethod.java
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/RenderLinkDirective.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java

The task wanted a link. But is that the right solution? Is the user expected to download it and try to unzip manually? Although, we would have to store the archive exceptionally as a part of the report, which we normally don't do unless --keepWorkDirs .
So I am only adding the path.

T842 Add the path to the archive that failed to unzip

---

config/impl/src/main/java/org/jboss/windup/config/metadata/RuleProviderRegistryCacheImpl.java
decompiler/impl-procyon/src/main/java/org/jboss/windup/decompiler/procyon/WindupJarTypeLoader.java
rules-base/impl/src/main/java/org/jboss/windup/rules/files/FileMappingGraphChangedListener.java
rules-base/impl/src/main/java/org/jboss/windup/rules/files/FileMappingLifecycleListener.java
rules-java-archives/addon/src/main/java/org/jboss/windup/rules/apps/java/archives/listener/ArchiveIdentificationLifecycleListener.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverHibernateMappingRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossEjbDescriptorRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossWebDescriptorRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/ResolveJBossEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/ResolveJBossLegacyEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/ResolveJBossWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/jbpm3/DiscoverJBossJbpmProcessFilesRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/orion/ResolveOrionEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/spring/ResolveSpringHibernateJPADataSourceRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/weblogic/ResolveWebLogicEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/weblogic/ResolveWebLogicWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/EnvironmentReferenceService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/VendorSpecificationExtensionService.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverHardcodedIPAddressRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/ArchivePackageNameIdentificationLifecycleListener.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMapping.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMappingRegistry.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/DiscoverXmlFilesRuleProvider.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/service/XmlFileService.java
rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/EnhancedEntityResolver2.java

- logger must use fully qualified class name (to support filtering by "org.jboss.windup")

Use FQCN for logger

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsExtensionXmlRuleProvider.java

Required classifications' title changes:
- “WebSphere WS Extension” → “WebSphere web service extension descriptor (ibm-webservices-ext)”
- “WebSphere WS Binding” → “WebSphere web service binding descriptor (ibm-webservices-bnd)”

WINDUPRULE-250+251 Rename 'WebSphere WS Extension/Binding'

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/ConsoleProgressMonitor.java

Currently the console doesn't give any indication when each line was printed. Date & time at the beginning of each line could be useful.

WINDUP-1559 Add timestamps to the console output

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/GetEffortDescriptionForPoints.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/IterableToListMethod.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/SortApplicationsListMethod.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/WindupVertexListModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/rules/CreateApplicationListReportRuleProvider.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl

This is sorting it at three places - first when adding it to the graph, which doesn't keep it sorted.
Then when generating it to the report, and then in JavaScript.
I am keeping all of them - 1st in case it starts keeping order, 2nd because it is necessary now, and the 3rd in case we get a request to sort it on the page by different criteria.

WINDUP-1494 sort apps case insensitive

---

graph/api/src/main/java/org/jboss/windup/graph/model/BelongsToProject.java
graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/HasApplications.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassModel.java

`BelongsToProject` is actually used on multiple places.
- https://github.com/windup/windup/blob/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologiesStatsService.java#L259
https://github.com/windup/windup-web/blob/master/addons/web-support/impl/src/main/java/org/jboss/windup/web/addons/websupport/rest/graph/EJBResourceImpl.java#L68 (which is now causing build failures on windup-web)
We should rather fix its behavior to deal correctly with shared libraries. Or find some better solution how to group data to project.

Revert deleting BelongsToProject

---

reporting/impl/src/main/resources/reports/templates/source.ftl

I tried to create it in `div.container-fluid` and not in `$(window)` (see [._create() method](https://christophercliff.com/sausage/docs/jquery.sausage.html#section-6)) but, after debugging, it doesn’t work (found on open issue on sausage repo [issue-9](https://github.com/christophercliff/sausage/issues/9))
Final solution: override top value in CSS to equal `#main-navbar`’s height using JS.
Tested with application `rhq-enterprise-server-ear-1.3.0.EmbJopr.1.3.0-4.ear`
in source for file `rhq-portal.war/WEB-INF/classes/ApplicationResources.properties` for `Hard-coded IP address` rule.
See [WINDUP-1659](https://issues.jboss.org/browse/WINDUP-1659) for screenshots

WINDUP-1659 Source code page:orange refs hidden from top nav bar

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/DiscoverWebXmlTest.java
rules-java-ee/tests/src/test/resources/web-xml/geronimo-web.xml
rules-java-ee/tests/src/test/resources/web-xml/web.xml

The issue:
1. The rule searches for "web-app" tag and if finds it in in the configuration file for geronimo `geronimo-web.xml` (it's not a regular `web.xml` file)
2. `geronimo-web.xml` has a `<naming:resource-ref>` definition, [this line from DiscoverWebXmlRuleProvider](https://github.com/windup/windup/blob/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java#L192) is executed 
3. but what is called `res-ref-name` in `web.xml`, in `geronimo-web.xml` is called `ref-name` so method [processElement from DiscoverWebXmlRuleProvider](https://github.com/windup/windup/blob/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java#L211) return an object without name field
4. then …

WINDUP-1665 DiscoverWebXmlRuleProvider fix for geronimo-web-xml

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyIdentified.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyUsageStatisticsModelExists.java

- added handling for `EjbBeanBaseModel` otherwise windup/windup-rulesets#263 wasn't able to add the technologies it finds
- after talking with @jsight, using `findAllByProperty(TechnologyUsageStatisticsModel.NAME, this.technologyName);` has better performance than `findAll();` that is still there commented to be used to debug in this phase of heavy creation of new rules

WINDUPRULE-289 Adding EjbBeanBaseModel handling

---

config-xml/schema/windup-jboss-ruleset.xsd
reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologyTag.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologyTagExists.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/TechnologyTagExistsHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/TechnologyTagHandler.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyIdentified.java

This PR fixes:
- [WINDUP-1682](https://issues.jboss.org/browse/WINDUP-1682) "_Create a TechnologyTag operation as well as handlers so that this can be supported in xml rules_"
- [WINDUP-1687](https://issues.jboss.org/browse/WINDUP-1687) "_windup-jboss-ruleset.xsd: wrong "lineitem-exists" definition_"
- [WINDUP-1688](https://issues.jboss.org/browse/WINDUP-1688) "_Multiple <rulePath> tags in XML tests_"
This PR is related to:
- #1177 because this PR makes #1177 obsolete and hence to be closed without merging it
- windup/windup-rulesets#267 because new XML rules can be created to discover libraries usage.
This PR contains:
- new `<technology-tag>` for `<perform>` operation in XML rules with
- text within the tag used as technology name (e.g. `Apache Wicket (embedded)`, `Spring MVC …

WINDUP-1682 WINDUPRULE-285 WINDUP-1687 WINDUP-1688

---

pom.xml

Better support for `Iterable`.
Sorry for the new branch, I forgot github creates them in upstream.

Upgrade Freemarker 2.3.23 to 2.3.26-incubating

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/JavaClassHandler.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassAnnotationFilteringTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/handlers/AnnotationConditionHandlerTest.java
rules-java/tests/src/test/resources/handler/annotationcondition.rhamt.xml
rules-java/tests/src/test/resources/handler/annotationcondition.windup.xml
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/AnnotationMultipleDs.java

This PR fixes the issue in [WINDUP-1732](https://issues.jboss.org/browse/WINDUP-1732)
- `org.jboss.windup.rules.apps.java.xml.JavaClassHandler#processElement` enhanced to better handle these three conditions:
- `<annotation-type>` allows both blank and valued `name` attribute
- `<annotation-list>` *now* allows blank `name` attribute to handle some nested annotation case, using the `value` value due to [`ReferenceResolvingVisitor.addAnnotationValues`](https://github.com/windup/windup/blob/master/java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java#L664)
- `<annotation-literal>` does *not* allow blank `name` attribute
- `org.jboss.windup.rules.java.handlers.AnnotationConditionHandlerTest` tests (w/ test files `annotationcondition.[windup,rhamt].xml`) the …

WINDUP-1732 <annotation-list> w/o 'name' attribute

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerUtil.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/IterableToListMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/SortFilesByPathMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/SortProjectTraversalsByPathMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/SortProjectsByPathMethod.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
rules-java-ee/addon/src/main/resources/reports/templates/hibernate.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jboss/jboss-ejb3.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jboss/jboss-web.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jbpm.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/FindFilesNotClassifiedOrHinted.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/IterableHasContent.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/SortDependencyArchivesByPathMethod.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/SortDependencyGroupArchiveByPathMethod.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/mavenize/MavenStructureRenderer.java
rules-java/api/src/main/resources/reports/templates/hardcoded_ip_addresses.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

Seems to work fine. I didn't check all reports but no errors were thrown with sample app.

Use freemarker updates

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
config/api/src/main/java/org/jboss/windup/config/AbstractPathConfigurationOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OutputPathOption.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/NoInputOrOutputPathTest.java

https://issues.jboss.org/browse/WINDUP-1730
I created new test for faililing soon `NoInputOrOutputPathTest`
I am not able to shift Target prompt if none is given as it would fail on validation.

WINDUP-1730: fixing validation of input/output options

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ReportService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossEjbDescriptorRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossWebDescriptorRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/GenerateJBossEjbDescriptorTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/GenerateJbossWebDescriptorTest.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformation.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/service/XsltTransformationService.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformationHandlerTest.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XMLTransformationTest.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XMLTransformationXMLRulesTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java

The generated files from [`GenerateJBossWebDescriptorRuleProvider`](https://github.com/windup/windup/blob/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossWebDescriptorRuleProvider.java) and [`GenerateJBossEjbDescriptorRuleProvider`](https://github.com/windup/windup/blob/master/rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossEjbDescriptorRuleProvider.java) are now placed inside folders path representing the projects they belong to in order to have a unique path to them and so having the files with _standard_ and _default_ names `jboss-web.xml` and `jboss-ejb3.xml` as requested in the [WINDUP-1726](https://issues.jboss.org/browse/WINDUP-1726)
To achieve this it has been refactored …

WINDUP-1726 Generated files' name

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/AbstractListCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/AbstractListCommandWithoutFurnace.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListSourceTechnologiesCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTagsCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTargetTechnologiesCommand.java

On average, an execution of RHAMT CLI with one of the following flags `--listTags`, `--listSourceTechnologies` or`--listTargetTechnologies` tooks about 5 seconds to execute.
In this 5 seconds, about 1.5-2 seconds are spent in a for loop in [XMLRuleProviderLoader](https://github.com/windup/windup/blob/master/config-xml/addon/src/main/java/org/jboss/windup/config/parser/XMLRuleProviderLoader.java#L120) due to loading of more than 100 rules files, each taking between 15-20 milliseconds.
The remaining 3 seconds are spent for starting and then shutting down Furnace and scanning the classpath for all Java addons.
With the changes in this PR, the sources/targets/tags are not retrieved  from rules anymore but they're read from the `help.xml` file with the result that running every command now …

WINDUP-1724 Reduce list {source,target,tag} commands execution time

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverHardcodedIPAddressRuleProvider.java
rules-java/tests/src/test/resources/staticip/other.xml
rules-java/tests/src/test/resources/staticip/staticips.properties

This PR fixes these three (adding also test cases) false positives for `Hard-coded IP addresses` rule :
- `<td>optional/castor-0.9.5.1-xml.jar</td>`
- `<device user_agent="AUDIOVOX-CDM9500/111.030 UP.Browser/5.0.4.1 (GUI)" fall_back="audiovox_cdm9500_ver1" id="audiovox_cdm9500_ver1_sub111030"/>`
- `BUILDINFO=JBoss Inc. [jhalli] (Linux 2.6.27.21-170.2.56.fc10.x86_64)`

WINDUPRULE-275 Rule 'Hard-coded IP addresses' too many matches

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/help/Help.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/help/OptionDescription.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OverwriteOption.java

[`org.jboss.windup.config.ConfigurationOption#isRequired`](https://github.com/windup/windup/blob/master/config/api/src/main/java/org/jboss/windup/config/ConfigurationOption.java#L43) is now handled in the [`OptionDescription`](https://github.com/windup/windup/blob/master/bootstrap/src/main/java/org/jboss/windup/bootstrap/help/OptionDescription.java) so that it can be displayed in the output of the help command for every option.

WINDUP-1767 CLI to describe what parameters are required

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/AbstractListCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListSourceTechnologiesCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTagsCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTargetTechnologiesCommand.java

The first commit has only the changes for `ListTagsCommand`.
If these changes are good, then i'll apply the same to `ListSourceTechnologiesCommand` and `ListTargetTechnologiesCommand`.
With these changes:
- executing CLI only with `--listTags` option still executes directly w/o any delay
- executing CLI with `--listTags` and `--userRulesDirectory /path/` options takes 5 seconds because it needs a `RuleProviderRegistryCache` from Furnace to get all the available tags from all the rules available

WINDUP-1758 WINDUP-1768 CLI  option in list* commands

---

tests/src/test/java/org/jboss/windup/tests/bootstrap/ListTechnologiesAndTagsCommandsTest.java

Executing `ListTechnologiesAndTagsCommandsTest` in central CI there was a NPE on [line 33 of `AbstractListCommandWithoutFurnace.getOptionValuesFromHelp`](https://github.com/windup/windup/blob/master/bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/AbstractListCommandWithoutFurnace.java#L33) due to having a `help.xml` cache file w/o the `<available-options>` section for options `target`, `source` and `includeTags`.
This situation was generated by the execution of the [`DisplayHelpCommandTest`](https://github.com/windup/windup/blob/master/tests/src/test/java/org/jboss/windup/tests/bootstrap/DisplayHelpCommandTest.java) that generates `help.xml` file w/o `<available-options>` section for options `target`, `source` and `includeTags` because it extends …

WINDUP-1773 Fix for failing tests on CI

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/NoInputOrOutputPathTest.java

The test didn't cover the right case because `""` was one of the element in the [`args`](https://github.com/windup/windup/blob/master/bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java#L72) array while if the command `rhamt-cli --input something --output --target eap` is executed there's no `""` value in the `args` array.

WINDUP-1774 CLI --output option handling

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/listener/ContainerStatusListener.java

The issue is happening on central CI so in order to better investigate it, i add the output of the whole Furnace instance **only** when it happens that input option is unrecognized due to having an empty acceptable options list because of Furnace instance being "wrong" (we're searching what's wrong).
The idea is to merge it and wait for the first failure on central CI to retrieve the information.

WINDUP-1747 Bootstrap integration tests fails on CI

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/XmlFile.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/validators/XmlFileNameValidator.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/validators/XmlFileXpathValidator.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XmlFileParameterizedTest.java
rules-xml/tests/src/test/resources/parameterizationtests/file-suffix1.xml
rules-xml/tests/src/test/resources/parameterizationtests/file-suffix2.xml

The `ParameterizedPatternResult` should be submitted only if the `XMLFile` condition is missing the XPath condition and not every time the file name pattern matches like it happened in [XmlFileNameValidator#isValid](https://github.com/windup/windup/compare/master...mrizzi:WINDUP-1879?expand=1#diff-885e00361e6e936a1a98a6636548f2d7L33) w/o having evaluated if there's also an XPath condition to be checked.
So the `ParameterizedPatternResult` submit has been moved to [XmlFile#registerAndSubmitResultsFor](https://github.com/windup/windup/compare/master...mrizzi:WINDUP-1879?expand=1#diff-3a9eccf2ac145f087bd0f09958ba1655R310) to be better handled.
Thanks to @jsight for the help in the analysis of this issue 👍

WINDUP-1879 Fix XmlFile condition

---

config/api/src/main/java/org/jboss/windup/config/metadata/MetadataBuilder.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheCoherenceLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheCommonsJcsLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheDynacacheLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheEhcacheLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheGlobalLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheHazelcastLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheIgniteLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheInfinispanLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheJBossCacheLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheJcacheLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheMemcachedLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheOscacheLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheShiftOneLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/cache/DiscoverEmbeddedCacheSwarmCacheLibraryRuleProvider.java

1. changed all the DiscoverEmbeddedCache*LibraryRuleProvider to have the cloud-readiness target so that they will be fire only when cloud-readiness is one of the analysis' targets
2. fixed target versionRange management

WINDUP-1915 DiscoverEmbeddedCache*LibraryRuleProvider add cloud-readiness target

---

config/api/src/main/java/org/jboss/windup/config/metadata/MetadataBuilder.java

Fix for handling the [`versionRange` default `""`](https://github.com/windup/windup/blob/4.0.x/config/api/src/main/java/org/jboss/windup/config/metadata/Technology.java#L25) implemented some lines above for [source technologies](https://github.com/windup/windup/blob/4.0.x/config/api/src/main/java/org/jboss/windup/config/metadata/MetadataBuilder.java#L131) to the target technologies.
Ported from https://github.com/windup/windup/pull/1277/files#diff-5b1e5adb9656972a3df7ca157f6b94a1

Fix for managing versionRange technology default

---

reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml

This fixes the missing mapping for logging which results, without the fix, in non-rendering reports if a rule for logging is added.
Attached are the screenshots from my local test on that branch.

add mapping for Logging to tech report boxes on UI

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJPAAnnotationsRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/DiscoverJPAAnnotationsTest.java
rules-java-ee/tests/src/test/resources/jpa/BaseEntity.java
rules-java-ee/tests/src/test/resources/jpa/SubclassWithDiscriminator.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/IndexJavaSourceFilesRuleProvider.java

https://issues.jboss.org/browse/WINDUP-698

WINDUP-698: JPA tables not resolved for Entity that extends base class

---

reporting/impl/src/main/resources/reports/templates/techReport-boxes.ftl

The tech report boxes use a different font size (12pt) than for instance the Issues page (12px).
I kept the headers for the boxes at 12pt.
This led to too early line breaks in the tech boxes (as browser window is maximised with a 15" screen), since the 12pt got rendered on my current test box as 16px - plus it's not really consistent.
While being there I did very minor changes to the font sizes of the JavaEE /Embedded text (they now match the size of e.g. "Migration Mandatory"on the issues page) and the text for the tiers (Connect, Sustain, etc. - they now match the size in the bubble map) - it's not perfect, but it's more consistent now.
Of course, when minimising the browser window, this will happen eventually, but higher consistency plus lesser line breaks on "standard screens" is …

change techReport-boxes font-sizes to be more consistent with the other reports

---

bom/pom.xml
bootstrap/pom.xml

The `<classifier>forge-addon</classifier>` was missing for `windup-server-provider-spi` artifact and adding it should avoid any need for providing the [`windup-server-provider-spi` version](https://github.com/windup/windup-web/blob/master/addons/messaging-executor/addon/pom.xml#L30) during the release process (this causes a failure during automatic release).

WINDUP-2101 Adding missing classifier to windup-server-provider-spi artifact

---

reporting/api/src/main/java/org/jboss/windup/reporting/category/IssueCategoryRegistry.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java

https://issues.jboss.org/browse/WINDUPRULE-355

WINDUPRULE-355 Move informational rules to a dedicated issue category

---

reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/Sha1HexMethod.java
reporting/impl/src/main/resources/reports/templates/dependency_graph.ftl
rules-java/api/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/dto/DependencyGraphItem.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateDependencyGraphDataRuleProvider.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureExplodedAppTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

https://issues.jboss.org/browse/WINDUP-2237
- fixes the exception during the dependency graph report generation
- adds a node in the graph for the exploded application (considered as a WAR archive)
- adds the test for the dependency graph generation for the  `--explodedApp` use case

WINDUP-2237 Fix the exception during graph generation

---

reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/techreport/TechReportService.java

Quickfix for [this issue](https://issues.jboss.org/browse/WINDUP-2177?focusedCommentId=13665230&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13665230)
@m-brophy you are more familiar and experienced than me in handling this maps-of-maps-of-maps stuff so if you feel it should work without the `null` check, please tell me.
@PhilipCattanach if you want to test this solution, it should work

WINDUP-2177 Fix for rendering issue found during UAT

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java
utils/src/main/java/org/jboss/windup/util/TarUtil.java

- new environmental property `FULL_TAR_ARCHIVE` to force the creation of a Tar file with everything found inside the input path directory
- the ability to provide a list of paths' prefixes to be excluded from the tar archive

WINDUP-2258 Enhanced TarUtil to exclude some files from archiving

---

reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/techreport/TechReportService.java

results map created for techbox report was skipping some of the results, finding that the techstat was not included in the application. This fix amends how that section of the code determines if a stat is to be included in an application's techbox report.

WINDUP-2179: summary and detail tech report count discrepancy

---

rules-java-project/addon/src/main/java/org/jboss/windup/project/condition/Artifact.java
rules-java-project/tests/src/test/java/org/jboss/windup/project/condition/test/ArtifactTest.java

A rule with a `when` condition like
```xml
<when>
<project>
<artifact groupId="org.hibernate" artifactId="{type}" />
</project>
</when>
```
was not working due to this bug.

WINDUPRULE-378: parameterized rule|project|artifactId bugfix

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js
reporting/impl/src/main/resources/reports/templates/application_list.ftl

https://issues.redhat.com/browse/WINDUP-2518
Added horizontal alignment to labels
Before:
After:

WINDUP-2518: Application List - Label alignment and Runtime hover over

---

rules-java-ee/addon/pom.xml

https://issues.redhat.com/browse/WINDUPRULE-403
This dependency has to be added in order to have [`org.jboss.windup.ext.groovy.GroovyWindupRuleProviderLoader.getCompositeClassloader`](https://github.com/windup/windup/blob/master/config-groovy/addon/src/main/java/org/jboss/windup/ext/groovy/GroovyWindupRuleProviderLoader.java#L159) to install this `windup-rules-java-ee` addon when executing Groovy rules like `singleton-sessionbean-groovy-00001` in https://github.com/windup/windup-rulesets/pull/392

WINDUPRULE-403 Added 'windup-config-groovy' dependency to use 'windup-rules-java-ee' in Groovy rules

---

rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContent.java
rules-base/tests/src/test/java/org/jboss/windup/rules/apps/condition/FileContentTest.java

https://issues.redhat.com/browse/WINDUP-2544
Added the test with a rule with a parameter `foo` and without a file name pattern condition: without the fix the test fails.

WINDUP-2544 Fix <filecontent> XML condition

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/tests/src/test/java/org/jboss/windup/reporting/CSVExportingTest.java

https://issues.redhat.com/browse/WINDUP-2591
`--skipReports` option works in [WindupProcessorImpl](https://github.com/windup/windup/blob/master/exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java#L351-L371) on filtering out all the report related phases from the analysis.
In this PR I detached the `ExportCSVFileRuleProvider` from `PostReportGenerationPhase` (skipped if `--skipReports` is set) and attached it to the `DependentPhase` but placing it "in the same place" it was within the ordered list of analysis' phases: after the `PostReportGenerationPhase` has started and before the `AttachApplicationReportsToIndexRuleProvider` (like it was before this change)

WINDUP-2591 Moved to DependentPhase to avoid interation with '--skipReports' option

---

bootstrap/pom.xml
rules-java/api/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/DependencyVisitor.java
rules-xml/api/pom.xml

https://issues.redhat.com/browse/WINDUP-2910
Updated [ASM](https://asm.ow2.io/index.html) dependency to let the BeforeDecompileClassesRuleProvider rule to work with JDK 11 built applications.
* ASM depedency upgrade fixed the exception `ASM was unable to parse class file` from `ClassFilePreDecompilationScan` reported in [this comment](https://issues.redhat.com/browse/WINDUP-2910?focusedCommentId=15615130&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15615130)
* The visitor Opcodes' definition has been changed to `ASM7` to prevent this exception during decompilation:
```
Failed when iterating [v[155672]={w:winduptype: [FileModel, JavaClassFileModel], fileName: Message.class, size: 8274, windupGenerated: false, filePath: …
```

WINDUP-2910 Analyze Applications that have been built with JDK11

---

pom.xml

With Maven 3.8.1, the project doesn't build due to:
```
[ERROR] Failed to execute goal on project windup-graph-impl:
Could not resolve dependencies for project org.jboss.windup.graph:windup-graph-impl:jar:5.2.1-SNAPSHOT:
Failed to collect dependencies at org.janusgraph:janusgraph-berkeleyje:jar:0.3.1 -> com.sleepycat:je:jar:7.4.5:
Failed to read artifact descriptor for com.sleepycat:je:jar:7.4.5: Could not transfer artifact com.sleepycat:je:pom:7.4.5 from/to maven-default-http-blocker (http://0.0.0.0/):
Blocked mirror for repositories: [oracleReleases (http://download.oracle.com/maven, default, releases+snapshots), spring-releases (http://repo.spring.io/libs-release-remote/, default, releases)]
```
This PR fixes this issue.

Setup Oracle Maven repo mirror with https

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClass.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationListCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationLiteralCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationTypeCondition.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassAnnotationFilteringTest.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/regex/SimpleAnnotatedClass.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/regex/SimpleSingleMemberAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/regex/SimpleTestAnnotation.java

Currently, if you try to run a rule like
```xml
<rule id="WOLAMissingClassesRule">
<when>
<javaclass references="javax.ejb.RemoteHome">
<location>ANNOTATION</location>
<annotation-literal name="value" pattern="{WOLAMissingClassesRule_annotation_fields}" />
</javaclass>
</when>
<perform>
<hint title="WOLAMissingClassesRule" effort="2">
<message>Some WebSphere z/OS Optimized Local Adapters APIs are unavailable</message>
</hint>
</perform>
<where param="WOLAMissingClassesRule_annotation_fields">
<matches pattern="com\.ibm\.websphere\.ola\.ExecuteHome" />
</where>
</rule>
```
You'll get an error that the parameter WOLAMissingClassesRule_annotation_fields isn't found in the rule and the scan won't run. This is because the code that checks for required parameter names in the javaClass condition …

Enable use of parameters in annotation conditions

---

README.asciidoc

Changes the example command found in the README file to a currently working one:
bin/mta-cli --target eap7 --input samples/jee-example-app-1.0.0.ear
- `bin/winup` seems to be an old name for the script
- `--target eap` doesn't work in the current version, it asks for a specific eap version.

Changes cli file and --target value in README example

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java

Effort to leverage the `IgnoredFileModel` model (created in [ArchivePackageNameIdentificationGraphChangedListener](https://github.com/windup/windup/blob/81cabeee805314c867bed721a9dfb84f9d60cf6f/rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/ArchivePackageNameIdentificationGraphChangedListener.java#L62)) to skip the analysis of `3rd Party Archive`s.

WINDUP-3307 Exclude '3rd Party Archive' from analysis

---

graph/api/src/main/java/org/jboss/windup/graph/model/IgnoredArchiveModel.java
rules-java-archives/addon/src/main/java/org/jboss/windup/rules/apps/java/archives/listener/ArchiveIdentificationGraphChangedListener.java
rules-java-archives/tests/src/test/java/org/jboss/windup/rules/apps/java/archives/IgnoreArchivesRulesetTest.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/ArchivePackageNameIdentificationGraphChangedListener.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/UnzipArchivesToOutputRuleProvider.java

This PR modifies the behaviour of the POM processing. If an archive is known and has been set to be ignored, now it will still be added to the graph. This is so that its information is available at a later stage for the Dependencies report to be filled. Otherwise, the Dependencies report will be missing most of the information, which comes from the POMs. Also, moved `IgnoreArchiveModel` to be along `ArchiveModel`.
See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3388).

[WINDUP-3388] Fix Dependencies report when --analyzeKnownLibraries is false

---

tests/pom.xml

No need to run the "addon-install" goal if the tests are going to be skipped so better to skip it as well

Skip Forge addon installation if skipTests is provided

---

rules-java/api/src/main/resources/reports/templates/about_windup.ftl

https://issues.redhat.com/browse/WINDUP-3455

[WINDUP-3455] - Update attribution for Red Hat Standard Icons

---

pom.xml

https://issues.redhat.com/browse/WINDUP-3363

WINDUP-3363: changed default tool label to be just 'Windup'

---

.github/workflows/pr_build_jdk11.yml

divided `windup-build` into `windup-build-with-unit-tests-1`, `windup-build-with-unit-tests-2` and `windup-tests`.
`windup-tests` just tests the module the name reflects.
The other two job, `windup-build-with-unit-tests-X` are a way for dividing in a 1-hour each the jobs to cover the remaining tests.
In the end the waiting time for the tests will move from more than 3 hours to something about 1 hour.
PS: the failures in other builds are unrelated to this PR but caused by changes in https://github.com/windup/windup/pull/1515

Divided 'tests' module testing from other modules testing

---

decompiler/impl-fernflower/pom.xml
decompiler/impl-procyon/pom.xml

The `wicket-core` test dependency declaration is useless so it can be safely removed.

Removed useless 'wicket-core' artifact test dependency declaration

---

.github/workflows/pr_build_jdk11.yml
.github/workflows/pr_build_jdk11_dependents.yml

Enabled GH Jobs execution for 'releases/**' branches, both PR and push events

---

.github/workflows/pr_build_jdk11_dependents.yml

It fixes the failure in `windup-quickstarts-build` execution in #1565

Added 'ref' value for windup-quickstarts build

---

rules-java-diva/addon/pom.xml

Excluded 'org.eclipse.core.runtime' artifact from 'diva-core' dependency

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java

https://issues.redhat.com/browse/WINDUP-3596
The console log looks like:
```
Execution failed due to disk space issue in the output path. Please check the field 'freeDiskLimit' in the next message: it represents the minimum free space required (in bytes)
(JE 18.3.12) Disk usage is not within je.maxDisk or je.freeDisk limits and write operations are prohibited: maxDiskLimit=0 freeDiskLimit=107,374,182,400 adjustedMaxDiskLimit=-107,374,182,400 maxDiskOverage=0 freeDiskShortage=97,035,079,680 diskFreeSpace=10,339,102,720 availableLogSize=-97,035,079,680 totalLogSize=1,427 activeLogSize=1,427 reservedLogSize=0 protectedLogSize=0 protectedLogSizeMap={}
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
at …
```

Added DiskLimitException management to provide better log

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/DefaultTechnologyTagComparator.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/TechnologyTagService.java
reporting/tests/src/test/java/org/jboss/windup/reporting/service/TechnologyTagServiceTest.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJpaConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/jbpm3/DiscoverJBossJbpmProcessFilesRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/orion/ResolveOrionWebXmlRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/EjbXmlParsingTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSeamBookingSourceTest.java
utils/pom.xml

https://issues.redhat.com/browse/WINDUP-3663
Technology tags fixed (with their tests) :
- `EJB XML` from `DiscoverEjbConfigurationXmlRuleProvider`
- `JPA XML` from `DiscoverJpaConfigurationXmlRuleProvider` 
- `Web XML` from `DiscoverWebXmlRuleProvider`
- `JBoss Process Image` from `DiscoverJBossJbpmProcessFilesRuleProvider`
- `Orion Web XML` from `ResolveOrionWebXmlRuleProvider`
Fixed also the `DefaultTechnologyTagComparator` with a new test added in `TechnologyTagServiceTest#testFindTechnologyTagsByProject`

WINDUP-3663 Fixed some Java EE tech tag version management

---

config-xml/schema/windup-jboss-ruleset.xsd
reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologyTag.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologyTagExists.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/TechnologyTagExistsHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/TechnologyTagHandler.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureJEEExampleTest.java
tests/src/test/xml/rules/technology-usage/embedded-framework-technology-usage.windup.xml
tests/src/test/xml/rules/technology-usage/embedded-framework.windup.xml

https://issues.redhat.com/browse/WINDUP-3664
- added `version` attribute to `technology-tag` tag that works also with `where` parameters
- added `version` attribute (evaluated as a regexp) to `technology-tag-exists` tag in order to be able to test the above new attribute in XML rules and tests
- enhanced integration tests to cover these new attributes

WINDUP-3664 Added 'version' attribute to both 'technology-tag' and 'technology-tag-exists' tags

---

pom.xml

Latest version of Maven 3.9.0 is by default installed in Windows and MacOS. Linux still uses Maven 3.8.7 but soon it should change.
Maven 3.9.0 removed the injection of `plexus-utils`. Maven plugins that depend of that dependency must be upgraded (maintainers of each maven plugin). In our case (users of a maven plugin affected by this change) we can set manually the problematic dependency until the maintainer of the plugin makes changes on it. Read more at https://maven.apache.org/docs/3.9.0/release-notes.html#potentially-breaking-core-changes

Fix maven 3.9.0 compatibility

---

pom.xml

https://docs.janusgraph.org/changelog/#version-063-release-date-february-18-2023
https://github.com/JanusGraph/janusgraph/releases/tag/v0.6.3

Bump janusgraph-0.6.3 tinkerpop-3.5.5

---

.github/workflows/pr_build_jdk11.yml

Fixed Maven to version '3.8.7' for 'windup-tests' job 

---

.github/workflows/pr_build_jdk11_dependents.yml

The scope of this change is to have the `windup-quickstarts-build` job to run again since it has been broken by the latest Ubuntu GitHub runner version (ref. https://github.com/actions/runner-images/issues/7216).

Fixed Maven to version '3.8.7' for 'windup-quickstarts-build' job

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJsonSummaryRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProviderTest.java

https://issues.redhat.com/browse/WINDUP-3720
closes #1603 
Changes:
- reverted changes in `CreateIssueSummaryDataRuleProvider` introduced with #1518 
- created a dedicate rule for creating the JSON summary, i.e. `CreateJsonSummaryRuleProvider`
- enhanced tests to cover the "skipReports" use case

WINDUP-3720 Decoupled JSON extract generation from reports rendering

---

test-util/pom.xml
test-util/src/main/java/org/jboss/windup/testutil/html/TestChromeDriverReportUtil.java

The issue has been triggered by the [Ubuntu 22.04 (20230313) Image Update](https://github.com/actions/runner-images/releases/tag/ubuntu22%2F20230313.1) that adopted Chrome 111 with which Selenium has the issue https://github.com/SeleniumHQ/selenium/issues/11750.
To "properly" solve it, [Using Java 11+ HTTP Client in Selenium 4.5.0 and beyond](https://www.selenium.dev/blog/2022/using-java11-httpclient/) guide has been applied but it spotted another issue: it caused `java.lang.ClassNotFoundException: java.net.http.HttpTimeoutException` due to [MODULES-392](https://issues.redhat.com/browse/MODULES-392).
The latter issues was fixed in JBoss Modules `1.9.2` but Furnace `2.29.1.Final` is using `jboss-modules:1.9.1.Final`.
So the `netty` driver has been adopted.
Furthermore, changes from …

Fix 'windup-tests' job

---

.github/workflows/backport.yml

Adds the full version missing in https://github.com/windup/windup/pull/1620

backport-github-action requires full version

---

pf-ui/src/main/webapp/src/shared/components/issues-table/issues-table.tsx

https://issues.redhat.com/browse/WINDUP-3843
Fixes the source filter being ignored bug in the Issues Table component when a target filter is also provided.

WINDUP-3843 Fix source filter for issues table component

---

reporting/impl/src/main/resources/reports/resources/css/topology-graph.css
reporting/impl/src/main/resources/reports/resources/js/app-dependency-graph.js
reporting/impl/src/main/resources/reports/templates/dependency_graph.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/dto/DependencyGraphItem.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureExplodedAppTest.java

This is a fix for the topology graph currently unfortunately broken for "JAR" applications.
The fix adds a node to display "JAR" applications and "JAR" libraries embedded within another "JAR".

Topology graph fix - Display JAR apps and JARs in JARs

---

config/api/src/main/java/org/jboss/windup/config/RuleSubset.java

When developing rules, there's a log entry which can be repeated many times: 
```
INFO: Rule [javaee-pom-to-quarkus from file:/home/mrizzi/git/forked/windup-rulesets/rules/rules-reviewed/quarkus/javaee/javaee-pom-to-quarkus.windup.xml] matched and will be performed.
```
But this adds (almost) no value to rule's developer because it refers to ruleset without specifying the rules and hence no helping debugging issues letting the user to understand which rule failed.
With this change the log now looks like
```
INFO: Rule [javaee-pom-to-quarkus from file:/home/mrizzi/git/forked/windup-rulesets/rules/rules-reviewed/quarkus/javaee/javaee-pom-to-quarkus.windup.xml - javaee-pom-to-quarkus-00030] matched and will be performed.
```
which makes it clear the rule `javaee-pom-to-quarkus-00030` (from …

RuleSubset: enhanced the 'matched and will be performed' log entry

---

config/api/src/main/java/org/jboss/windup/config/parameters/ParameterizedGraphCondition.java

Enhanced log when "double frame" is added to know which is the variable accountable for the situation.
For example, while developing [rule `cdi-to-quarkus-groovy-00010`](https://github.com/windup/windup-rulesets/pull/946/files#diff-3b93765efad2246fdcb7d256a6909256c2db7e37a3c0236719aaaf9118ec97d8R70-R114) with multiple `as` fields, this helped a lot providing a log entry like `resultSetStores already had a ParameterValueStore for frame (varname 'injectClassDeclaration')`

ParameterizedGraphCondition: added var name into warning log

---

config/api/src/main/java/org/jboss/windup/config/projecttraversal/ProjectTraversalCache.java
reporting-data/addon/src/main/java/org/jboss/windup/reporting/data/rules/DataGatheringRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/ClearProjectTraversalCacheRuleProvider.java

Analyzing the JVM's memory while running the test for the windup-rulesets project, it turned out:
1. 59.93% of memory used for GraphRewrite instances referenced in the static AbstractApiRuleProvider.executorServiceMap map
2. Once fixed previous, 22.88% of memory for GraphRewrite instances referenced in the static ProjectTraversalCache.applicationToProjectCache map

Fix some memory leaks in windup-rulesets testing

---

pf-ui/src/main/webapp/src/pages/application-edit/pages/dashboard/components/efforts-section.tsx

https://issues.redhat.com/projects/WINDUP/issues/WINDUP-3903
The issue describes the scales in two sections of the `Dashboard` page:
> Note from the ticket: `the upper one has decimals which are useless because SP are integers`
- The `Y` axis is generated automatically depending on the values set on the report. We are taking Patternfly as it is.
- If the max value of `Y` is too small it is expected to have decimals in the `Y` set of labels because the `Y` axis needs to have a minimum (around 6 or 7) labels to render. We must keep in mind that having decimal labels in the `y` axis has no impact on the accuracy of the values of each Bar in the Chart. The chart continues to be 100% valid.
in short words I don't think this specific point is bug neither I think that it will mislead any user in …

[WINDUP-3903]-Graphs has wrong scales

---

bom/pom.xml

This fixes
```
bad class file: /home/mrizzi/.m2/repository/org/eclipse/platform/org.eclipse.core.runtime/3.27.0/org.eclipse.core.runtime-3.27.0.jar(/org/eclipse/core/runtime/Plugin.class)
class file has wrong version 61.0, should be 55.0
[...]
[ERROR] /home/mrizzi/git/forked/windup/java-ast/addon/src/main/java/org/eclipse/jdt/core/dom/WindupASTParser.java:[257,46] error: cannot access Plugin
```
and 
```
java.lang.UnsupportedClassVersionError: Failed to link org/eclipse/core/resources/IResource (Module "org.jboss.windup.ast.windup-java-ast:6.3.0-SNAPSHOT_1a55c2ab-4120-40ba-b0b1-28f7e76e919d" from AddonModuleLoader): org/eclipse/core/resources/IResource has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes …
```

Exclude v3.27.0+ for org.eclipse.core.runtime artifact

---

bom/pom.xml

backport
- #1678
Changes
* Exclude v3.27.0+ for org.eclipse.core.runtime artifact
* Exclude v3.19.0+ for org.eclipse.core.resources artifact
Depends on
- https://github.com/windup/windup-maven-plugin/pull/48

[releases/6.1.z] Exclude v3.27.0+ for org.eclipse.core.runtime artifact ()

---

reporting/impl/src/main/resources/reports/resources/css/topology-graph.css
reporting/impl/src/main/resources/reports/resources/js/app-dependency-graph.js
reporting/impl/src/main/resources/reports/templates/dependency_graph.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/dto/DependencyGraphItem.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureExplodedAppTest.java

backport https://github.com/windup/windup/pull/1632
* Fix for the topology graph to be able to display "Jar" apps and "Jar" containing other "Jar" libraries.
* Updating tests to match the new number of archives in the graph

[releases/6.1.z] Topology graph fix backport 6.1.z

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-4055
https://issues.redhat.com/browse/WINDUP-4056
Objective: to upgrade `io.netty:netty-codec-http2` to the latest version `4.1.100.Final`

[WINDUP-4055], [WINDUP-4056] Upgrade io.netty:netty-codec-http2:jar to 4.1.100

---

bom/pom.xml

[WINDUP-4136](https://issues.redhat.com/browse/WINDUP-4136)
[WINDUP-4137](https://issues.redhat.com/browse/WINDUP-4137)
[WINDUP-4138](https://issues.redhat.com/browse/WINDUP-4138)

WINDUP-4136: upgrade commons-compress to v1.26.0

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

This will backport the following commits from `master` to `releases/6.3.z`:
- [WINDUP-4139: upgrade axios (#1728)](https://github.com/windup/windup/pull/1728)
Please refer to the [Backport tool documentation](https://github.com/sorenlouv/backport)

[releases/6.3.z] WINDUP-4139: upgrade axios (#1728)

---

bom/pom.xml
java-ast/addon/pom.xml

https://issues.redhat.com/browse/WINDUP-4200
In this way, Windup will properly log from , i.e.
```
2024-08-02 10:58 [53/1683] InitialAnalysisPhase - AnalyzeJavaFilesRuleProvider - AnalyzeJavaFilesRuleProvider_1
Status ERROR: org.eclipse.jdt.core code=4 Could not retrieve interfaces org.eclipse.jdt.internal.compiler.problem.AbortCompilation: Pb(324) The type org.eclipse.swt.widgets.Composite cannot be resolved. It is indirectly referenced from required .class files
2024-08-02 11:02 [54/1683] InitialAnalysisPhase - DiscoverHibernateMappingRuleProvider - DiscoverHibernateMappingRuleProvider_1
```

WINDUP-4200 Add org.eclipse.text runtime dependency

---

bom/pom.xml
java-ast/addon/pom.xml

https://issues.redhat.com/browse/WINDUP-4200
Backport
- https://github.com/windup/windup/pull/1745

[releases/6.3.z] WINDUP-4200 Add org.eclipse.text runtime dependency

---

bom/pom.xml

Hi Marco,
Can you review this PR please?
The vulnerability appears to be present in the https://mvnrepository.com/artifact/org.jsoup/jsoup/1.15.3.redhat-00003
So I've bumped the version

WINDUP-4201 vulnerability fix
