windup/windup

graph/api/src/main/java/org/jboss/windup/graph/listeners/BeforeGraphCloseListener.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
rexster/pom.xml
rexster/src/main/java/org/jboss/windup/graph/rexster/RexsterInitializer.java
rexster/src/test/java/org/jboss/windup/graph/rexster/test/RexsterTest.java

Implemented also the rexster closement.

WINDUP-435: Write tests for Rexster addon

---

bom/pom.xml

Offering this polished shiny version of updated BOM, as requested.

BOM update with proper style

---

config/api/src/main/java/org/jboss/windup/config/phase/ArchiveExtraction.java
config/api/src/main/java/org/jboss/windup/config/phase/ArchiveMetadataExtraction.java
config/api/src/main/java/org/jboss/windup/config/phase/ClassifyFileTypes.java
config/api/src/main/java/org/jboss/windup/config/phase/Decompilation.java
config/api/src/main/java/org/jboss/windup/config/phase/DiscoverProjectStructure.java
config/api/src/main/java/org/jboss/windup/config/phase/Discovery.java
config/api/src/main/java/org/jboss/windup/config/phase/Finalize.java
config/api/src/main/java/org/jboss/windup/config/phase/InitialAnalysis.java
config/api/src/main/java/org/jboss/windup/config/phase/Initialization.java
config/api/src/main/java/org/jboss/windup/config/phase/MigrationRules.java
config/api/src/main/java/org/jboss/windup/config/phase/PostFinalize.java
config/api/src/main/java/org/jboss/windup/config/phase/PostMigrationRules.java
config/api/src/main/java/org/jboss/windup/config/phase/PostReportGeneration.java
config/api/src/main/java/org/jboss/windup/config/phase/PostReportRendering.java
config/api/src/main/java/org/jboss/windup/config/phase/PreReportGeneration.java
config/api/src/main/java/org/jboss/windup/config/phase/ReportGeneration.java
config/api/src/main/java/org/jboss/windup/config/phase/ReportRendering.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/IsRulePhaseMethod.java
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
rules-java/src/main/java/org/jboss/windup/rules/apps/java/binary/DecompileArchivesRuleProvider.java

https://issues.jboss.org/browse/WINDUP-487

WINDUP-487: Document RulePhase implementations

---

rules-java-ee/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateHibernateReportRuleProvider.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/ip/CreateDiscoverStaticIPAddressReportRuleProvider.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverStaticIPAddressRuleProvider.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/ip/StaticIPLocationModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/ip/StaticIPLocationReportModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJavaIgnoredFilesReportRuleProvider.java
rules-java/src/main/resources/reports/templates/static_ip_addresses.ftl

Adds report for static IP addresses when they exist in Java, Property, or XML files.

Static ip addresses

---

frames/src/main/java/com/tinkerpop/frames/FramedElement.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ReportService.java
reporting/impl/pom.xml
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/EffortPointsToCssClass.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/MarkdownToHtmlMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/pegdown/WindupCodeBlockPlugin.java
reporting/impl/src/main/java/org/jboss/windup/reporting/pegdown/WindupCodeNode.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/HintHandler.java
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-base/api/src/main/java/org/jboss/windup/rules/files/model/FileLocationModel.java
rules-java-ee/src/main/resources/legacy/org.jboss.windup.rules.apps.legacy.java.WebLogicConfig.windup.xml
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/JavaTypeReferenceModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/TypeReferenceLocation.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryModeTest.java

https://issues.jboss.org/browse/WINDUP-501

WINDUP-501: Hints should support markdown in content/bodies

---

config/api/src/main/java/org/jboss/windup/config/phase/Initialization.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverFilesAndTypesRuleProvider.java
rules-java/src/main/resources/reports/templates/java_application.ftl

What about providing also Location if possible?

WINDUP-498: Application overview report display problems, not solutions

---

config/api/src/main/java/org/jboss/windup/config/GraphRewrite.java
config/api/src/main/java/org/jboss/windup/config/RuleSubset.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintBuilderIn.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintBuilderTitle.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/HintHandler.java
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java/src/main/resources/reports/templates/java_application.ftl
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java
tests/src/test/xml/XmlExample.windup.xml
tests/src/test/xml/exampleuserscript.xml

https://issues.jboss.org/browse/WINDUP-497

Hints should support content/bodies

---

rules-java/src/main/java/org/jboss/windup/rules/apps/java/ip/CreateStaticIPAddressReportRuleProvider.java

Added in icon for static IP address report.

Added in icon for static IP addresses report.

---

rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContent.java
rules-base/tests/src/test/java/org/jboss/windup/rules/apps/condition/FileContentTest.java
rules-java-ee/src/main/java/org/jboss/windup/rules/apps/javaee/model/EjbEntityBeanModel.java
rules-java-ee/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbAnnotationsRuleProvider.java
rules-java-ee/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/src/main/resources/reports/templates/ejb.ftl
rules-java/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/model/JavaSourceFileModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/JavaAnnotationTypeReferenceModel.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/VariableResolvingASTVisitor.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/AddClassFileMetadata.java
rules-java/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/IndexJavaSourceFilesRuleProvider.java
test-files/src_example/src/main/java/org/windup/examples/ejb/entitybean/SimpleEntity.java
test-files/src_example/src/main/java/org/windup/examples/ejb/entitybean/SimpleEntityNoTableName.java
test-files/src_example/src/main/java/org/windup/examples/ejb/messagedriven/MessageDrivenBean.java
test-files/src_example/src/main/java/org/windup/examples/ejb/simplestateful/SimpleStatefulEJB.java
test-files/src_example/src/main/java/org/windup/examples/ejb/simplestateless/SimpleStatelessEJB.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestEJBReportUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java

https://issues.jboss.org/browse/WINDUP-493

WINDUP-493: Add annotation scanning support to EJB discovery

---

rules-java/src/main/java/org/jboss/windup/rules/apps/java/config/CopyJavaConfigToGraphRuleProvider.java

Caused NPE in quickstarts tests

WINDUP-511 Fix NPE

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintSeverity.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/ClassificationAs.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/ClassificationDescription.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/ClassificationSeverity.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ReportFileModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/Severity.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/InlineHintService.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/ClassificationHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/HintHandler.java
reporting/tests/src/test/java/org/jboss/windup/reporting/handlers/ClassificationHandlerTest.java
reporting/tests/src/test/java/org/jboss/windup/reporting/handlers/HintHandlerTest.java
reporting/tests/src/test/resources/handler/classification.windup.xml
reporting/tests/src/test/resources/handler/hint.windup.xml

https://issues.jboss.org/browse/WINDUP-515

Add Severity to Hint (and Classification)

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/ParserContext.java
config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/RuleHandler.java
config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/RulesHandler.java
config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/perform/PerformHandler.java
config-xml/tests/src/test/java/org/jboss/windup/config/parser/XMLRuleProviderLoaderTest.java
config-xml/tests/src/test/resources/testxml/Test1.windup.xml
config/api/src/main/java/org/jboss/windup/config/RuleSubset.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverAllSpecifiedTest.java

https://issues.jboss.org/browse/WINDUP-518

WINDUP-518: XML Handlers do not support nested rules

---

pom.xml

http://s3.thinkaurelius.com/docs/titan/current/changelog.html

Upgrade Titan to 0.5.4. Numerous bugfixes.

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/maven/dao/MavenProjectService.java

https://issues.jboss.org/browse/WINDUP-544

WINDUP-544: StackOverflowException when generating Application report

---

rules-java-project/addon/src/main/java/org/jboss/windup/project/handlers/ArtifactHandler.java
rules-java-project/addon/src/main/java/org/jboss/windup/project/operation/LineItem.java
rules-java-project/tests/src/test/resources/xml/project.xml

'From' is used in other conditions to set input variable name on the stack. It may confuse people

Change from/to in the artifact to fromVersion/toVersion

---

graph/api/src/main/java/org/jboss/windup/graph/GraphTypeRegistry.java
graph/api/src/main/java/org/jboss/windup/graph/IndexType.java
graph/api/src/main/java/org/jboss/windup/graph/Indexed.java
graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextFactoryImpl.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/model/FileLocationModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassFileModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaSourceFileModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/PackageModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/project/MavenProjectModel.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/DoctypeMetaModel.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/NamespaceMetaModel.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/XmlFileModel.java

https://issues.jboss.org/browse/WINDUP-198

WINDUP-198: Initial implementation of annotation-based graph indices

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/ReportFileModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/DiscoverXmlFilesRuleProvider.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformation.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/service/XmlFileService.java
test-files/src_example_bad_maven/pom.xml
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/entitybean/SimpleEntity.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/entitybean/SimpleEntityNoTableName.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/messagedriven/MessageDrivenBean.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/messagedriven/MessageDrivenBean2.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/simplestateful/SimpleStatefulEJB.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/ejb/simplestateless/SimpleStatelessEJB.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/servlet/SampleServlet.java
test-files/src_example_bad_maven/src/main/java/org/windup/examples/servlet/SampleWebLogicServlet.java
test-files/src_example_bad_maven/src/main/resources/WEB-INF/web.xml
test-files/src_example_bad_maven/src/main/resources/springexample/spring-sample-file.xml
test-files/src_example_bad_maven/src/main/resources/test.properties
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureScanPackagesTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryMode2Test.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSoa5GatewaysRoutersTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceWithBadPOMTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSpringSmallTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupRulesetMetadataTest.java

https://issues.jboss.org/browse/WINDUP-528

WINDUP-528:  Quiet down the logging on unparseable XML files

---

rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/DiscoverXmlFilesRuleProvider.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/XMLDocumentCache.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/model/XmlFileModel.java
rules-xml/addon/src/main/java/org/jboss/windup/rules/apps/xml/service/XmlFileService.java
utils/src/main/java/org/jboss/windup/util/xml/XmlUtil.java

(will mark for review when I finish looking at XmlUtil)

Add XML caching functionality (based on bradsdavis and lincolnthree's work in this area)

---

decompiler/impl-procyon/src/main/java/org/jboss/windup/decompiler/procyon/ProcyonDecompiler.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/ProcyonDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/ZipEntryPackageFilter.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/AddClassFileMetadata.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/service/WindupJavaConfigurationService.java

Continuation of https://github.com/windup/windup/pull/535

Bradsdavis decompile filtering

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl

Fixed freemarker templates and css to properly show tables within panels; fixed definition lists CSS for when they are the last element in a panel, don't put bottom margin.

WINDUP-575: cleanup UI for consistency within panels

---

graph/api/src/main/java/org/jboss/windup/graph/model/LicenseModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverArchiveLicenseFilesRuleProvider.java

Indexes archive for LICENSE and NOTICE files.

WINDUP-579 - Created license indexer

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/IdentifiedArchiveFileFilter.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java

now leverages IdentifiedArchiveFileFilter.java to identify which files to index when the archive is "known."

WINDUP-577 - Index Certain Known Archive Files

---

config-xml/rule-schema.xsd

Tested all rules in windup-rulesets and updated documentation to have tutorial how to do it

XSD schema update

---

config/api/src/main/java/org/jboss/windup/config/query/Query.java
config/api/src/main/java/org/jboss/windup/config/query/QueryBuilderFind.java
config/tests/src/test/java/org/jboss/windup/config/QueryConditionTest.java

Add includingTypes() API to Query API

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/metadata/MetadataDescriptionHandler.java
config-xml/addon/src/main/java/org/jboss/windup/config/parser/metadata/MetadataTagHandler.java
config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/MetadataRootHandler.java
config-xml/rule-schema.xsd
config/api/src/main/java/org/jboss/windup/config/metadata/AbstractRulesetMetadata.java
config/api/src/main/java/org/jboss/windup/config/metadata/MetadataBuilder.java
config/api/src/main/java/org/jboss/windup/config/metadata/RuleMetadata.java
config/api/src/main/java/org/jboss/windup/config/metadata/RuleProviderMetadata.java
config/api/src/main/java/org/jboss/windup/config/metadata/RulesetMetadata.java

Continuation of https://github.com/windup/windup/pull/569

Mbriskar windup 606

---

config-xml/schema/windup-jboss-ruleset.xsd

Add maxOccurs to XSD

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java
java-ast/tests/src/test/java/org/jboss/windup/ast/java/test/JavaASTReferenceResolverTest.java
java-ast/tests/src/test/resources/testclasses/simple/ExampleWildcardImport.java

https://issues.jboss.org/browse/WINDUP-620

WINDUP-620: Return classreferences for wildcard imports

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/data/TypeReferenceLocation.java
java-ast/tests/src/test/java/org/jboss/windup/ast/java/test/JavaASTReferenceResolverTest.java
java-ast/tests/src/test/resources/testclasses/simple/FullNonImportedFQCNNotOnClasspath.java

Will be ready for review if the tests pass :)

WINDUP-635: <javaclass> doesn't pick up FQCN used without imports.

---

config/api/src/main/java/org/jboss/windup/config/RuleSubset.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/HibernateSessionFactoryModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JPAEntityModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JPANamedQueryModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateJPAReportRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJPAAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
test-util/src/main/java/org/jboss/windup/testutil/html/TestJPAReportUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

Continuation of: https://github.com/windup/windup/pull/609

Split out JPA entities from the rest of the entities

---

rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContent.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentFileName.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentFrom.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentFromImpl.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentHandler.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentMatches.java
rules-base/tests/src/test/java/org/jboss/windup/rules/apps/condition/FileContentTest.java
rules-base/tests/src/test/resources/filecontentstest/WriteToFile.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverStaticIPAddressRuleProvider.java

Continuation of: 
https://github.com/windup/windup/pull/615

Mbriskar windup 667

---

config-xml/schema/windup-jboss-ruleset.xsd
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/File.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContentHandler.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileFrom.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileHandler.java
rules-base/tests/src/test/java/org/jboss/windup/rules/apps/condition/FileTest.java
rules-base/tests/src/test/resources/xml/FileXmlExample.windup.xml

Introduced new condition because FileContent is not  suitable name for queries like "give me files with the given name". @sgilda should be informed about this change

WINDUP-676: Introduce new condition: File

---

pom.xml

to get support for switch() and then()
http://freemarker.org/docs/versions_2_3_23.html

Upgrade Freemarker

---

config/impl/src/main/java/org/jboss/windup/config/loader/RuleLoaderImpl.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/RenderRuleLinkDirective.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetProblemSummariesMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/ProblemSummary.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/CreateProblemCentricReportRuleProvider.java
reporting/impl/src/main/resources/reports/templates/problem-centric-report.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverStaticIPAddressRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/FindUnboundJavaReferencesRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaHintsClassificationsTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/ignore/JavaIgnoreRegexesTest.java

https://issues.jboss.org/browse/WINDUP-674

WINDUP-674: Problem-centric report

---

config/api/src/main/java/org/jboss/windup/config/operation/IterationProgress.java

I am currently running a test that will take 2 hours, so I have time to add simple features :-)

IterationProgress has default variable name hardcoded

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
utils/src/main/java/org/jboss/windup/util/PathUtil.java

tested in both cases on real applications, tested also with exportCSVTest (but not with all the windup tests)

WINDUP-734 + WINDUP-728: Fix exportCSV bugs

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/tests/src/test/resources/test-exports/app1.csv
reporting/tests/src/test/resources/test-exports/app2.csv

this change was requested by Tobias

CSV change ; to ,

---

rules-java/api/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverStaticIPAddressRuleProvider.java

https://issues.jboss.org/browse/WINDUP-755
This should fix https://issues.jboss.org/browse/WINDUP-673 as well.

WINDUP-755: In Migration Issues Report, roll up all static IP issues into 1

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/WindupVertexListModel.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/model/FileReferenceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/EjbRemoteServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JaxRSWebServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JaxWSWebServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/RMIServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/RemoteServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateRemoteReportRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJPAAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJaxRsAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJaxWSAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverRemoteEjbRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverRmiRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/EjbRemoteServiceModelService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/JaxRSWebServiceModelService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/JaxWSWebServiceModelService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/RMIServiceModelService.java
rules-java-ee/tests/pom.xml
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/service/EjbRemoteServiceModelServiceTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/service/JaxRSWebServiceModelServiceTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/service/JaxWSWebServiceModelServiceTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/service/RMIServiceModelServiceTest.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/JavaTypeReferenceModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/FindUnboundJavaReferencesRuleProvider.java

https://issues.jboss.org/browse/WINDUP-773

WINDUP-773: Fix the appearance of duplicate services in the remote services report

---

graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java

https://issues.jboss.org/browse/WINDUP-697

WINDUP-697: Titan graph fails to initialize when localhost cannot be resolved

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-base/api/src/main/java/org/jboss/windup/rules/files/model/FileLocationModel.java
rules-java/api/src/main/resources/reports/templates/java_application.ftl

Issue to close when/if merged: https://issues.jboss.org/browse/WINDUP-764

    WINDUP-764  Some XML file classifications have the file's content instead of title.

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
rules-java/api/src/main/resources/reports/templates/java_application.ftl

Added a radius on "table-bordered" to make sure that striped tables having a grey last row look nice.
Fixed padding issue on the main java_application page.

Fixing HTML/CSS markup (rounded corners and added padding)

---

reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/windupfreemarkerfunctions.ftl

Fixed the markup for the RuleProviderSummary and the FreemarkerFuctions pages.

Fixed markup - RuleProviderSummary and FreemarkerFunctions pages

---

config-xml/schema/windup-jboss-ruleset.xsd

fixed again the required hint title XSD definition

WINDUP-746 added hint title as mandatory attribute

---

rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl

Removing a flying apostrophe

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

https://issues.jboss.org/browse/WINDUP-784

WINDUP-784: Fix sorting to be numeric instead of alphanumeric

---

forks/frames/src/main/java/com/tinkerpop/frames/FramedElement.java
forks/frames/src/main/java/com/tinkerpop/frames/modules/javahandler/JavaMethodHandler.java
graph/api/src/main/java/org/jboss/windup/graph/model/comparator/FilePathComparator.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/SortFilesByPathMethod.java

This appears to net 7-10% in my testing.

Slight refactoring to file sort code and tweaked the FramedElement to cache lookups

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/EjbMessageDrivenModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/EjbSessionBeanModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/ThreadPoolModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateServerResourceRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/ResolveServerResourceLinksRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/weblogic/ResolveWeblogicEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/resources/reports/templates/jboss/jboss-ejb3.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/EjbXmlParsingTest.java
test-files/ejb/weblogic-ejb-test/weblogic-ejb-jar.xml

- Extract Thread Pool configurations from Weblogic descriptors
- Report on Thread Pools on Server Resources
- Link to Thread Pool setup in EAP
See screenshots of feature on JIRA: 
https://issues.jboss.org/browse/WINDUP-604

WINDUP-604 - Added support for ThreadPools to model

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClass.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassTest.java

It used to happen that JavaClass.compiledPattern didn't work in cases where JavaClass.from() was used.

JavaClass from/as fix

---

reporting/impl/src/main/resources/reports/templates/include/navbar.ftl

https://issues.jboss.org/browse/WINDUP-790

WINDUP-790: Mark current page as active

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
config/api/src/main/java/org/jboss/windup/config/AbstractPathConfigurationOption.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverAllSpecifiedTest.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverDefaultListVariableTest.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverDefaultSingleVariableTest.java
config/tests/src/test/java/org/jboss/windup/config/iteration/RuleIterationOverTypesTest.java
config/tests/src/test/java/org/jboss/windup/config/iteration/payload/when/RuleIterationWhenTest.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/ExplodedAppInputOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/InputPathOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OutputPathOption.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
ui/addon/src/main/java/org/jboss/windup/ui/WindupCommand.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupCommandRuleFilteringTest.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupCommandTest.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupUpdateDistributionCommandTest.java

This is the --input part, and doesn't work as the rest of the app and all tests would need to start using WindupConfiguration#getInputPaths(), addInputPath() etc. - which is out of scope of this task, and Jess already did that.

Task #256 - Implement multiple application entry into Windup

---

config/api/src/main/java/org/jboss/windup/config/operation/Iteration.java
config/api/src/main/java/org/jboss/windup/config/operation/IterationProgress.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/BatchASTProcessor.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/MarkdownToHtmlMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/rendering/RenderReportRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/FernflowerDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/ProcyonDecompilerOperation.java
utils/src/main/java/org/jboss/windup/util/threading/WindupExecutors.java

An experiment to multithread the reporting process

Multithreaded report rendering

---

rules-java/api/src/main/resources/reports/templates/java_application.ftl

WRT WINDUP-764 - make the template simpler while keeping the resulting visuals.

Simplify java-app.ftl  (AFTER PR 684)

---

decompiler/api/src/main/java/org/jboss/windup/decompiler/api/DecompilationFailure.java
decompiler/api/src/main/java/org/jboss/windup/decompiler/api/DecompilationListener.java
decompiler/api/src/main/java/org/jboss/windup/decompiler/api/DecompilationResult.java
decompiler/api/src/main/java/org/jboss/windup/decompiler/decompiler/AbstractDecompiler.java
decompiler/api/src/test/java/org/jboss/windup/decompiler/DecompilerTestBase.java
decompiler/impl-fernflower/src/main/java/org/jboss/windup/decompiler/fernflower/FernFlowerResultSaver.java
decompiler/impl-fernflower/src/main/java/org/jboss/windup/decompiler/fernflower/FernflowerDecompiler.java
decompiler/impl-fernflower/src/test/java/org/jboss/windup/decompiler/fernflower/FernflowerDecompilerTest.java
decompiler/impl-procyon/src/main/java/org/jboss/windup/decompiler/procyon/ProcyonDecompiler.java
decompiler/impl-procyon/src/test/java/org/jboss/windup/decompiler/procyon/ProcyonDecompilerTest.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/AbstractDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/FernflowerDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/ProcyonDecompilerOperation.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

With this PR, every single .class file (A$1.class, A.class, A$InternalClass.class) will be connected with its decompiled part (A.java).
I also tried to create AbstractDecompiler so there is not that much duciplicits between the two implementations. However there is still some, so this is just a first step.

Decompilation fix

---

reporting/impl/src/main/resources/reports/resources/css/windup-source.css

The line is a bit distrurbing.
Also, put the comments a bit closer together so it's easier to see that they belong to the same line.

Remove the black line in source report

---

config-xml/schema/windup-jboss-ruleset.xsd

this should guide rule authors more easily before they test them.

WINDUP-781 adding use=required for mandatory attributes

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
rules-java/api/src/main/resources/reports/templates/java_application.ftl

e.g.: Oracle proprietary type reference 5×

WINDUP-754 Group the identical hint labels with number -

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/GenerateCompletionDataCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/GenerateHelpCacheCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/help/Help.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/help/OptionDescription.java

https://issues.jboss.org/browse/WINDUP-846

WINDUP-846: Windup bootstrap runs slow even for showing help usage

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
config/api/src/main/java/org/jboss/windup/config/metadata/RuleProviderRegistryCache.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/SourceOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/TargetOption.java

https://issues.jboss.org/browse/WINDUP-854

WINDUP-854: Invalid value of the --target option doesn't cause an error

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/ExcludeTagsOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/InputPathOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OfflineModeOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OutputPathOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OverwriteOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/SourceOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/TargetOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/UserIgnorePathOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/UserRulesDirectoryOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/config/ExcludePackagesOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/config/ScanPackagesOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/config/SourceModeOption.java

https://issues.jboss.org/browse/WINDUP-848

WINDUP-848: Enhance Windup help usage for --packages option

---

reporting/impl/src/main/resources/reports/templates/index.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl

https://issues.jboss.org/browse/WINDUP-839

WINDUP-839: Send feedback links at the bottom of the application list and the top of the application overview page are broken

---

graph/api/src/main/java/org/jboss/windup/graph/frames/FrameBooleanDefaultValue.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/GetEffortDescriptionForPoints.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/EffortReportModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetProblemSummariesMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/ProblemSummary.java
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
test-util/src/main/java/org/jboss/windup/testutil/html/TestMigrationIssuesReportUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java

https://issues.jboss.org/browse/WINDUP-858

WINDUP-858: Migration Issues report should be updated

---

config/api/src/main/java/org/jboss/windup/config/operation/Iteration.java
config/tests/src/test/java/org/jboss/windup/config/iteration/IterationAutomicCommitTest.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
pom.xml
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassWithoutHintTest.java

Should be ready to go, but I haven't run all tests yet

Tweaks to the commit interval and graph configuration that greatly improve graph performance

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/DefaultTechnologyTagComparator.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/TechnologyTagLevel.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/TechnologyTagService.java

https://issues.jboss.org/browse/WINDUP-899

WINDUP-899: Technology tags appear in a random order

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetProblemSummariesMethod.java

https://issues.jboss.org/browse/WINDUP-891

WINDUP-891: Migration Issues Report: Mandatory type issues should be first in the table

---

graph/api/src/main/java/org/jboss/windup/graph/model/ProjectModel.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/embedded.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/server-resources.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
reporting/impl/src/main/resources/reports/templates/windupfreemarkerfunctions.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateUnparsableFilesReportRuleProvider.java
rules-java/api/src/main/resources/reports/templates/compatible_files.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

https://issues.jboss.org/browse/WINDUP-883

WINDUP-883: Top menu bar hides page title when window narrowed

---

exec/api/src/main/java/org/jboss/windup/exec/configuration/options/SourceOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/TargetOption.java

https://issues.jboss.org/browse/WINDUP-847

WINDUP-847 enhanced option description of Source and Target options

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/InlineHintService.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/GetEffortDetailsForProjectMethod.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/GetEffortForFile.java
reporting/impl/src/main/java/org/jboss/windup/reporting/freemarker/SortFilesByPathMethod.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/include/effort_util.ftl
reporting/tests/src/test/java/org/jboss/windup/reporting/ClassificationServiceTest.java
reporting/tests/src/test/java/org/jboss/windup/reporting/InlineHintServiceTest.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/IterableHasContent.java
rules-java/api/src/main/resources/reports/templates/java_application.ftl

https://issues.jboss.org/browse/WINDUP-900

WINDUP-900: The application list should display effort categories

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/RenderApplicationPieChartDirective.java
rules-java/api/src/main/resources/reports/resources/js/report-index-graphs.js
rules-java/api/src/main/resources/reports/templates/report_index.ftl

https://issues.jboss.org/browse/WINDUP-910

WINDUP-910: Rework report_index to put less information on each "row"

---

config-xml/schema/windup-jboss-ruleset.xsd
reporting/api/src/main/java/org/jboss/windup/reporting/model/Severity.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java

Comes with https://github.com/windup/windup-rulesets/pull/115

    WINDUP-918  Ruleset XSD: Reflect the enumerated attributes.

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/classloader.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl
reporting/impl/src/main/resources/reports/templates/server-resources.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
reporting/impl/src/main/resources/reports/templates/windupfreemarkerfunctions.ftl
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
rules-java-ee/addon/src/main/resources/reports/templates/hibernate.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jbpm.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl
rules-java/api/src/main/resources/reports/resources/js/report-index-graphs.js
rules-java/api/src/main/resources/reports/templates/compatible_files.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/api/src/main/resources/reports/templates/report_index.ftl
rules-java/api/src/main/resources/reports/templates/static_ip_addresses.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

https://issues.jboss.org/browse/WINDUP-903

WINDUP-903: Move help text to an always visible box

---

test-files/pom.xml

WINDUP-885 Make windup-test-files produce an empty main artifact so it passes JBoss Nexus validation.

---

graph/api/src/main/java/org/jboss/windup/graph/model/ArchiveModel.java
graph/api/src/main/java/org/jboss/windup/graph/model/ProjectModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JarManifestModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJarDependencyReportRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverAdditionalProjectDetails.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverArchiveManifestFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/service/JarManifestService.java
rules-java/api/src/main/resources/reports/templates/jar_report.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/DiscoverAdditionalProjectDetailsTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/ExportCsvTest.java

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/60

Creates a JAR dependency report

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java
java-ast/tests/src/test/java/org/jboss/windup/ast/java/test/JavaASTReferenceResolverTest.java
java-ast/tests/src/test/resources/testclasses/unavailablesuperclass/UnavailableSuperclass.java

@mareknovotny - This doesn't completely solve your problem, but maybe it can be a starting point?

Tweaked to also mark 'implements' for interfaces implemented by superclasses

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJPAAnnotationsRuleProvider.java

https://issues.jboss.org/browse/WINDUP-972

WINDUP-972 fixing NPE when no EntityBean found

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

https://issues.jboss.org/browse/WINDUP-967

WINDUP-967: Fixed sort order handling of commas in numbers

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaHintsClassificationsTest.java

https://issues.jboss.org/browse/WINDUP-950

WINDUP-950: Fix for case where the title parameterization fails

---

config/impl/src/main/java/org/jboss/windup/config/metadata/RuleProviderRegistryCacheImpl.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java

https://issues.jboss.org/browse/WINDUP-973

WINDUP-973: incomprehensible NPE when a XML rule is wrong

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

https://issues.jboss.org/browse/WINDUP-968

WINDUP-968: Table sorting is broken if the subrows are open

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

Doesn't really fix WINDUP-966 but reduces the resulting script by ~30 %.

Reduce the resulting script by ~30 %.

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DiscoverPackagesCommand.java
utils/src/main/java/org/jboss/windup/util/ZipUtil.java

I need them in maven-indexer. Related to WINDUP-984

Move few generic methods to ZipUtils.

---

config-xml/schema/windup-jboss-ruleset.xsd
java-ast/addon/src/main/java/org/jboss/windup/ast/java/ReferenceResolvingVisitor.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/data/annotations/AnnotationClassReference.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClass.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClassBuilderAt.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationListCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationLiteralCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/annotation/AnnotationTypeCondition.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/JavaTypeReferenceModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/annotations/JavaAnnotationTypeReferenceModel.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/AnnotationConditionHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/AnnotationListConditionHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/AnnotationLiteralConditionHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/AnnotationTypeConditionHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/xml/JavaClassHandler.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/JavaClassAnnotationFilteringTest.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/handlers/AnnotationConditionHandlerTest.java
rules-java/tests/src/test/resources/handler/annotationcondition.windup.xml
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/basic/SimpleAnnotatedClass.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/basic/SimpleSingleMemberAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/basic/SimpleTestAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/AnotherComplexAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/ComplexAnnotatedClass.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/ExampleComplexAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/ExampleNestedAnnotation.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/annotationtests/complex/ExampleNestedAnnotationLevel2.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestJavaApplicationOverviewUtil.java

https://issues.jboss.org/browse/WINDUP-974

WINDUP-974: Support queries based upon annotation values

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

Amends https://github.com/windup/windup/pull/889 with a better fix.

Used update instead of the previous single row approach

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/TypeInterestFactory.java

From https://github.com/windup/windup/pull/878/commits/24a5de4912dc874fb55fef16a11b98c16703e1f3

Javadoc improvement

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformation.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformationHandlerTest.java
rules-xml/tests/src/test/resources/xslttransform/sample.xml
rules-xml/tests/src/test/resources/xslttransform/xsl-with-include.xsl
rules-xml/tests/src/test/resources/xslttransform/xslt.transform.windup.xml

https://issues.jboss.org/browse/WINDUP-999

WINDUP-999: NPE on xsl:include

---

rules-java/api/src/main/resources/reports/templates/report_index.ftl

WINDUP-1016 Fix report_index.ftl - missing closing </div>

---

reporting/impl/src/main/resources/reports/templates/ruleprovidersummary.ftl

Before/after screenshots attached to WINDUP-1032.

WINDUP-1032 fix breaking table in rule providers report

---

config-xml/schema/windup-jboss-ruleset.xsd
rules-base/api/src/main/java/org/jboss/windup/rules/files/FileMapping.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/FileMappingFrom.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/FileMappingTo.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/FileMappingWithID.java
rules-base/impl/src/main/java/org/jboss/windup/rules/files/FileMappingHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMapping.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMappingHandler.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMappingWithOrganization.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/packagemapping/PackageNameMappingWithPackagePattern.java

https://issues.jboss.org/browse/WINDUP-1003

WINDUP-1003: Attach IDs to all filemapping and package-mapping rules

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

https://issues.jboss.org/browse/WINDUP-1033

WINDUP-1033: migration report: issue un-collapses on re-sort

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetProblemSummariesMethod.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureCatchallTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/134

Tweaked migration issues application level report to match the others

---

reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
reporting/tests/src/test/java/org/jboss/windup/reporting/ClassificationServiceTest.java

(this also adds a comment to the relevant code, as well as unit test so that we don't forget this edge case again)

Fixed a problem with the classification stats

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerUtil.java

https://issues.jboss.org/browse/WINDUP-1081

Fix WINDUP-1081

---

graph/api/src/main/java/org/jboss/windup/graph/Indexed.java
graph/api/src/main/java/org/jboss/windup/graph/Indexes.java
graph/api/src/main/java/org/jboss/windup/graph/TitanUtil.java
graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
graph/api/src/main/java/org/jboss/windup/graph/service/FileService.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/File.java
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/FileContent.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/JavaClass.java

https://issues.jboss.org/browse/WINDUP-1073

WINDUP-1073: FileContent and File have a very slow approach to file search

---

reporting/api/src/main/java/org/jboss/windup/reporting/service/TechnologyTagService.java

https://issues.jboss.org/browse/WINDUP-1092

WINDUP-1092: Generating source reports is now spectacularly slow

---

rexster/addon/src/main/java/org/jboss/windup/graph/rexster/RexsterInitializer.java

I rewrote the extracting jar files as it caused filenotfound exceptions on some environment

fixed unforseen issues while extracting jar files

---

config/tests/src/test/java/org/jboss/windup/config/iteration/IterationAutomicCommitTest.java
graph/api/src/main/java/org/jboss/windup/graph/FramedElementInMemory.java
graph/api/src/main/java/org/jboss/windup/graph/GraphContext.java
graph/impl/src/main/java/org/jboss/windup/graph/GraphContextImpl.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverDuplicateArchiveProjectsRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/UnzipArchivesToOutputRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/mavenize/PackagesToContainingMavenArtifactsIndex.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/rules/ValidateXmlFilesRuleProviderWithInternetTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java

Adds a convenience commit method and also makes the service() method return the interface that is proxyable instead of a concrete class.

Tweaks to the API to support windup-web

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateAboutWindupReportRuleProvider.java

https://issues.jboss.org/browse/WINDUP-1127

WINDUP-1127 adding About report to global navigation panel

---

config-xml/schema/windup-jboss-ruleset.xsd
graph/api/src/main/java/org/jboss/windup/graph/model/QuickfixModel.java
graph/api/src/main/java/org/jboss/windup/graph/model/QuickfixType.java
graph/api/src/main/java/org/jboss/windup/graph/service/QuickfixService.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintQuickfix.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/HintText.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Quickfix.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/ClassificationQuickfix.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/ClassificationHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/HintHandler.java
reporting/impl/src/main/java/org/jboss/windup/reporting/xml/QuickfixHandler.java
reporting/tests/src/test/java/org/jboss/windup/reporting/handlers/QuickfixHandlerTest.java
reporting/tests/src/test/resources/handler/quickfix.windup.xml
tooling/api/pom.xml
tooling/api/src/main/java/org/jboss/windup/tooling/data/Classification.java
tooling/api/src/main/java/org/jboss/windup/tooling/data/Hint.java
tooling/api/src/main/java/org/jboss/windup/tooling/data/Quickfix.java
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionResultsImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/data/ClassificationImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/data/HintImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/data/LinkImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/data/QuickfixImpl.java
tooling/impl/src/main/java/org/jboss/windup/tooling/data/ReportLinkImpl.java
tooling/tests/src/test/java/org/jboss/windup/tooling/ExecutionBuilderTest.java

taiga task #231 Basic quick fix support in rules and tooling

added quickfix element for task 233

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
config/api/src/main/java/org/jboss/windup/config/AbstractRuleProvider.java
config/api/src/main/java/org/jboss/windup/config/SkipReportsRenderingOption.java
exec/api/src/main/java/org/jboss/windup/engine/predicates/RuleProviderWithDependenciesPredicate.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
exec/tests/src/test/java/org/jboss/windup/exec/test/SkippingReportsRenderingTest.java
graph/api/src/main/java/org/jboss/windup/graph/model/WindupConfigurationModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/tests/src/test/java/org/jboss/windup/reporting/CSVExportingTest.java
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionBuilderImpl.java

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/262

Taiga t262

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/help/Help.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/help/OptionDescription.java

@johnsteele http://paste2.org/kB4H082z - Let me know if this works for you.

Added detailed option information to the help.xml file

---

rules-java-ee/addon/pom.xml
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/GeneralStatsItemModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/GeneralStatsModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologiesStatsModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologiesStatsService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/generateModel.groovy
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/TechnologiesStatsRuleProvider.java
rules-java-ee/addon/src/main/scripts/generateModel.groovy
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassModel.java
tests/pom.xml
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryMode2Test.java

Squash before merging please.
This either needs https://github.com/windup/windup-web/pull/64 and Task #333
OR PR 64 minus commit b716876609

#290 Tech Report - #299 #319 #329 #328

---

pom.xml

Trying if it would work. Currently we are using version 2008-something.
1) The old versions are very buggy
2) Can't serialize proxies
3) The API is supposedly the same.

org.json:json:20160810

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/mavenize/MavenStructureRenderer.java

Freemarker wants /'s only in the path to the template.

WINDUP-1226 --mavenize fails on Windows

---

config/tests/src/test/java/org/jboss/windup/config/RuleProviderDisabledTest.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OnlineModeOption.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
graph/api/src/main/java/org/jboss/windup/graph/model/WindupConfigurationModel.java
reporting/impl/src/main/resources/reports/templates/include/navbar.ftl
reporting/impl/src/main/resources/reports/templates/include/navbar_macro.ftl
rules-base/api/src/main/java/org/jboss/windup/rules/files/condition/ProcessingIsOnlineGraphCondition.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/mavenize/MavenizeRuleProviderTest.java
rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/EnhancedEntityResolver2.java
rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/ValidateXmlFilesRuleProvider.java
rules-xml/impl/src/main/java/org/jboss/windup/rules/apps/xml/xml/ValidateXmlHandler.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/rules/AbstractXsdValidationTest.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/rules/ValidateXmlFilesRuleProviderWithInternetTest.java
tooling/tests/src/test/java/org/jboss/windup/tooling/ExecutionBuilderTest.java

Related: https://github.com/windup/windup-rulesets/pull/179

WINDUP-1221: Flip the default to offline mode and add an --online switch

---

reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/include/timestamp.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/source.ftl
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
rules-java-ee/addon/src/main/resources/reports/templates/hibernate.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jbpm.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl
rules-java/api/src/main/resources/reports/templates/about_windup.ftl
rules-java/api/src/main/resources/reports/templates/compatible_files.ftl
rules-java/api/src/main/resources/reports/templates/dependency_report.ftl
rules-java/api/src/main/resources/reports/templates/hardcoded_ip_addresses.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/api/src/main/resources/reports/templates/report_index.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

This is easier to recognize if reports are from the last or from old processing.

adding timestamps to reports

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
exec/api/src/main/java/org/jboss/windup/exec/updater/RulesetsUpdater.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/DisplayHelpCommandTest.java
ui/addon/src/main/java/org/jboss/windup/ui/RulesetUpdateChecker.java
ui/addon/src/main/java/org/jboss/windup/ui/WindupUpdateRulesetCommand.java
ui/tests/src/test/java/org/jboss/windup/addon/ui/WindupUpdateRulesetTest.java

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/447
code is commented out to preserve later enabling/updating the implementations.

taiga task #447 - disabled updating of rules

---

graph/api/src/main/java/org/jboss/windup/graph/GraphTypeManager.java

It was storing the added type String only instead of adding it

Fix GraphTypeManager.addProperty()

---

graph/api/src/main/java/org/jboss/windup/graph/model/BelongsToProject.java
graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
graph/api/src/main/java/org/jboss/windup/graph/service/ProjectService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/EjbBeanBaseModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/HasApplications.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JNDIResourceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JPAPersistenceUnitModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/PersistenceEntityModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/RemoteServiceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/ProjectTechnologiesStatsModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/ProjectTechnologiesStatsService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologiesStatsModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologiesStatsService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/stats/TechnologyKeyValuePairModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/TechnologiesStatsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/TechnologyKeyValuePairModelService.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/JavaClassModel.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSmallBinaryMode2Test.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java
tests/src/test/java/org/jboss/windup/tests/application/reports/technology/AppWithMultipleTechnologiesTest.java
tests/src/test/java/org/jboss/windup/tests/application/reports/technology/TechnologiesStatsServiceTest.java

Preparing common interface for filtering models by project.

Tech report filter

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbAnnotationsRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/JNDIResourceService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/JmsDestinationService.java

Improve detection of Topic/Queue based on annotation.

Add JMS type

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/PhaseHandler.java
config/api/src/main/java/org/jboss/windup/config/phase/RulePhaseFinder.java
exec/api/src/main/java/org/jboss/windup/engine/predicates/RuleProviderWithDependenciesPredicate.java

Refactor PhaseHandler, spin off RulePhaseFinder, split interface and impl where needed to get it through furnace

T550 Skip HTML reports rendering

---

bom/pom.xml
pom.xml

Comes with https://github.com/windup/windup-web/pull/272
which fails on something in TsModelGen.
Comes with https://github.com/windup/windup-quickstarts/pull/83

T617 Upgrade forge and furnace

---

bom/pom.xml
pom.xml

https://issues.jboss.org/browse/WINDUP-1328

WINDUP-1328 - Upgrade of Furnace to 2.25.4.Final

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
rules-java/api/src/main/resources/reports/resources/js/report-index-graphs.js
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java

Just until something like https://github.com/windup/windup/pull/1096 can be approved.

Fix charts to use category id and not display 0 items

---

exec/impl/src/main/java/org/jboss/windup/exec/DefaultRuleLifecycleListener.java

Fix for [https://issues.jboss.org/browse/WINDUP-1348](WINDUP-1348)

WINDUP-1348 Right number in rules' progress monitor

---

tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

Fixing tests for https://github.com/windup/windup/pull/1101

WINDUP-1348 Tests fixing

---

reporting/api/src/main/java/org/jboss/windup/reporting/service/ClassificationService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbExtensionXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsClientBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsExtBindingXmlRuleProvider.java

Other part: https://github.com/windup/windup-rulesets/pull/196
(Doesn't really depend)

T752 Make WebSphere descriptors mandatory

---

rules-java/api/src/main/resources/reports/templates/about_windup.ftl

https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/891

task891: changed About page - heading and links to docs/web

---

reporting/api/src/main/java/org/jboss/windup/reporting/category/IssueCategoryRegistry.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/CreateHardcodedIPAddressReportRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverHardcodedIPAddressRuleProvider.java

I am not exactly sure about the changes here. Because I don't exactly understand the existence of cloud-mandatory category. Feels like some confusion of terms.

T896 Hardcoded IP cloud-mandatory

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/ResolveJBossLegacyEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/weblogic/ResolveWebLogicEjbXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereWsExtBindingXmlRuleProvider.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureDuplicateTest.java

…l-descriptor-04000 XML rule
https://tree.taiga.io/project/rdruss-jboss-migration-windup-v3/task/1009

tasks 1009/1002/1007 - disabling classification due duplications

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossEjbDescriptorRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbBindingXmlRuleProvider.java

I didn't understand "This is overlapping with two other rules" but hopefully this is what was meant.

WINDUPRULE-214 dedup.

---

exec/api/src/main/java/org/jboss/windup/exec/configuration/options/UserIgnorePathOption.java
rules-java/impl/src/main/java/org/jboss/windup/rules/apps/java/config/GatherIgnoredFileNamesRuleProvider.java

https://issues.jboss.org/browse/WINDUP-1443

WINDUP-1443: adding rhamt-ignore.txt pattern for user ignores

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformation.java

related to https://github.com/windup/windup-rulesets/pull/245

WINDUPRULE-257 XSLT generated file not in migration issues page

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbBindingXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/websphere/ResolveWebSphereEjbExtensionXmlRuleProvider.java

subtasks WINDUPRULE-268 and 267 from https://issues.jboss.org/browse/WINDUPRULE-265

subtasks for https://issues.jboss.org/browse/WINDUPRULE-265

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEmbeddedJSFLibraryRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEmbeddedSeam2LibraryRuleProvider.java

fixing JSF embedded regex pattern
https://issues.jboss.org/browse/WINDUPRULE-260

WINDUPRULE-260: adding Seam 2 jars discovery rule provider

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DisplayHelpCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ServerModeCommand.java
config/api/src/main/java/org/jboss/windup/config/KeepWorkDirsOption.java
config/api/src/main/java/org/jboss/windup/config/RuleSubset.java
config/api/src/main/java/org/jboss/windup/config/SkipReportsRenderingOption.java
config/api/src/main/java/org/jboss/windup/config/operation/Iteration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/InputPathOption.java
exec/impl/src/main/java/org/jboss/windup/exec/DefaultRuleLifecycleListener.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerUtil.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/config/ScanPackagesOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/EnableCompatibleFilesReportOption.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DeleteWorkDirsAtTheEndRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/mavenize/MavenizeGroupIdOption.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/DisplayHelpCommandTest.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/CorrectParameterTest.java
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionBuilderImpl.java
ui/addon/src/main/java/org/jboss/windup/ui/DefaultValueAdapter.java
ui/addon/src/main/java/org/jboss/windup/ui/DistributionUpdater.java
ui/addon/src/main/java/org/jboss/windup/ui/RulesetUpdateChecker.java
ui/addon/src/main/java/org/jboss/windup/ui/WindupCommand.java
ui/addon/src/main/java/org/jboss/windup/ui/WindupUpdateDistributionCommand.java
ui/addon/src/main/java/org/jboss/windup/ui/WindupUpdateRulesetCommand.java
utils/src/main/java/org/jboss/windup/util/Util.java

https://issues.jboss.org/browse/WINDUP-1572

WINDUP-1572: replaced Windup strings in user facing messages

---

pom.xml
rules-tattletale/addon/pom.xml

Let's try this. I guess it needs building and running with that app.
I don't know which app that is though. Couldn't reproduce.

WINDUP-1595 Javassist is out of date in Tattletale

---

config-xml/pom.xml
forks/frames/pom.xml
pom.xml

https://issues.jboss.org/browse/WINDUP-1558
Using special profile findbugs as `mvn clean compile ... -Pfindbugs`

WINDUP-1558: adding Findbugs profile with static code analysis

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverHardcodedIPAddressRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/ip/DiscoverHardcodedIPAddressTest.java
rules-java/tests/src/test/resources/staticip/other.xml
rules-java/tests/src/test/resources/staticip/pom.xml

Continues: https://github.com/windup/windup/pull/1156

Mareknovotny windup 1614

---

rules-java/api/src/main/resources/reports/templates/report_index.ftl

https://issues.jboss.org/browse/WINDUP-1618

WINDUP-1618: removed additional reports table on index page

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

https://issues.jboss.org/browse/WINDUP-1617

WINDUP-1617: Removing panel 'Details'

---

reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
rules-java/api/src/main/resources/reports/templates/dependency_report.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

https://issues.jboss.org/browse/WINDUP-1619
I will try to fix the changes differently not including the table row in layout, but if you want to push this PR I don't care, but I think we can do better and simpler.

WINDUP-1619: Marc's style changes

---

rules-java/api/src/main/resources/reports/templates/dependency_report.ftl

https://issues.jboss.org/browse/WINDUP-1635

WINDUP-1635: Dependency Report styles fixed

---

graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/HibernateSessionFactoryModel.java

Add `BelongsToProject` interface to `HibernateSessionFactory`.

WINDUP-1590 - hibernate report, app level filtering

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/when/QueryHandler.java
config-xml/schema/windup-jboss-ruleset.xsd
config-xml/tests/pom.xml
config-xml/tests/src/test/java/org/jboss/windup/config/parser/xml/when/QueryHandlerTest.java
config-xml/tests/src/test/resources/query-handler.rhamt.xml
config/api/src/main/java/org/jboss/windup/config/query/Query.java
graph/api/src/main/java/org/jboss/windup/graph/GraphTypeManager.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyIdentified.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyUsageStatisticsModelExists.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyUsageStatisticsModelExistsHandler.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/TechnologyUsageStatisticsModelExistsHandlerTest.java
rules-java-ee/tests/src/test/resources/technology-identified/technology-usage-exists.windup.xml

This is an experiment that might make it easier to implement some of the technology report rules as xml. What do you think?

QueryHandler: Specify some basic graph queries via XML

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/CssFileModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/HtmlFileModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JsFileModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/markup/MarkupFileMappingRuleProvider.java

- added *Models to handle html, css and js files
- added `MarkupFileMappingRuleProvider` to map them all in just one step

WINDUPRULE-286 Models to handle markup technologies

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/xml/when/QueryHandler.java
config-xml/schema/windup-jboss-ruleset.xsd
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/DataSourceModel.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverHibernateConfigurationRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJpaConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/service/DataSourceService.java
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl

https://issues.jboss.org/browse/WINDUPRULE-295

WINDUPRULE-295 adding JTA discovery

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/model/JPAPersistenceUnitModel.java

This PR is preparatory for windup/windup-rulesets#271 as for [this comment](https://github.com/windup/windup-rulesets/pull/271#discussion_r141606702)

WINDUPRULE-292 JPAPersistenceUnitModel enhancement

---

reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

put the commented block to a FTL comment rather than HTML comment

Fix Migration Issues report FTL format;

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/freemarker/RenderLinkDirective.java

https://issues.jboss.org/browse/WINDUP-1653

WINDUP-1653: fixed anchor in file link

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateRemoteReportRuleProvider.java
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl

https://issues.jboss.org/browse/WINDUP-1743
This is primary targeting 4.0.x branch. After merging into that this needs to be merged into master too.

Windup 1743

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/ResolveJBossLegacyEjbXmlRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/ResolveJBossLegacyEjbXmlRuleProviderTest.java
rules-java-ee/tests/src/test/resources/discover-jndi/SomeFancyEjbBean.java
rules-java-ee/tests/src/test/resources/discover-jndi/jboss.xml

https://issues.jboss.org/browse/WINDUPRULE-194

WINDUPRULE-194: adding jndi recognition from remote-binding

---

reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/FreeMarkerIterationOperation.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/ReportService.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossEjbDescriptorRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/GenerateJBossWebDescriptorRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/GenerateJBossEjbDescriptorTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/GenerateJbossWebDescriptorTest.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformation.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/service/XsltTransformationService.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/apps/xml/operation/xslt/XSLTTransformationHandlerTest.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XMLTransformationTest.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XMLTransformationXMLRulesTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java

Cherry-picked commit 8db513b to branch 4.0.x as per request in [this comment on WINDUP-1726](https://issues.jboss.org/browse/WINDUP-1726?focusedCommentId=13483553&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13483553)

WINDUP-1726 Generated files' name (#1213)

---

rules-tattletale/addon/pom.xml

TODO: 
- Need to release `1.3` GA version.

WINDUP-1759 - Update tattletale version

---

rules-tattletale/addon/pom.xml

Updating tattletale (#1227)

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/Bootstrap.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/AbstractListCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListSourceTechnologiesCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTagsCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ListTargetTechnologiesCommand.java

* WINDUP-1758 CLI  option in list* commands
* WINDUP-1758 CLI option in list* commands: improved implementation
Ported #1219 to 4.0.x branch

WINDUP-1758 WINDUP-1768 CLI  option in list* commands (#1219)

---

tests/src/test/java/org/jboss/windup/tests/bootstrap/ListTechnologiesAndTagsCommandsTest.java

WINDUP-1773 Fix for failing tests on CI (#1232)

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/NoInputOrOutputPathTest.java

WINDUP-1774 CLI --output option handling (#1235)

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/NoInputOrOutputPathTest.java

This fixes [WINDUP-1776](https://issues.jboss.org/browse/WINDUP-1776) adding also a new test case
It has to be merged also on 4.0.x branch

WINDUP-1776 --output option NPE

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/NoInputOrOutputPathTest.java

WINDUP-1776 --output option NPE (#1237)

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/resources/js/windup-migration-issues.js
reporting/impl/src/main/resources/reports/templates/include/problem_summary.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

Optimized performance and fixed columns width
Porting #1233 to 4.0.x branch

WINDUP-1770 static reports performance (#1233)

---

rules-java/api/src/main/resources/reports/templates/about_windup.ftl

Same as windup/windup-web#538 for static reports

WINDUP-1754 Remove the Contributors box on the About page

---

reporting/impl/src/main/resources/reports/resources/js/windup-migration-issues.js

I removed Drag & Drop code. Was there any usage for it? Can it be removed, or should I keep it there and fix it?

WINDUP-1791 - Fix text selection (master)

---

reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

Add css class prefix to prevent overriding some other page styles

WINDUP-1795 - Resize migration-issues table width

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJavaIgnoredFilesReportRuleProvider.java
rules-java/api/src/main/resources/reports/templates/about_windup.ftl

WINDUP-1793 Links redirected 

---

rules-tattletale/addon/src/main/java/org/jboss/windup/rules/apps/tattletale/TattletaleRuleProvider.java

Do not create tattletale menu item if report is not generated

WINDUP-1794 - Tattletale 404

---

rules-tattletale/addon/src/main/java/org/jboss/windup/rules/apps/tattletale/TattletaleRuleProvider.java

Do not create tattletale menu item if report is not generated

WINDUP-1794 - Tattletale 404 (master)

---

reporting/impl/src/main/resources/reports/resources/css/tech-report-punchcard.css
reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl

Update tech bubble report to keep heading on top while scrolling table content.
Screenshot:
[![Screenshot_from_2017-12-14_13-39-25.png](https://s33.postimg.org/3qqfugx9r/Screenshot_from_2017-12-14_13-39-25.png)](https://postimg.org/image/wgdbr419n/)

WINDUP-1799 - tech report heading

---

rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/XmlFile.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/validators/XmlFileNameValidator.java
rules-xml/api/src/main/java/org/jboss/windup/rules/apps/xml/condition/validators/XmlFileXpathValidator.java
rules-xml/tests/src/test/java/org/jboss/windup/rules/xml/XmlFileParameterizedTest.java
rules-xml/tests/src/test/resources/parameterizationtests/file-suffix1.xml
rules-xml/tests/src/test/resources/parameterizationtests/file-suffix2.xml

Back porting of #1267 
Not exactly the same code because of the switch to TP3 on master so [addVertex(null, ProjectModel.class)](https://github.com/windup/windup/compare/4.0.x...mrizzi:WINDUP-1879_4.0.x?expand=1#diff-8f24f401ef2a9a7d31bedf18ef55c35aR219) and [.addVertex(null, FileModel.class);](https://github.com/windup/windup/compare/4.0.x...mrizzi:WINDUP-1879_4.0.x?expand=1#diff-8f24f401ef2a9a7d31bedf18ef55c35aR221) have been used here.

WINDUP-1879 Fix XmlFile condition (#1267)

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/CreateSpringBeanReportRuleProvider.java

WINDUP-1914 CreateSpringBeanReportRuleProvider remove source

---

utils/src/main/java/org/jboss/windup/util/TarUtil.java

Just an experiment... needs to be documented and planned out fully to integrate into the regular build.

Http serializer support

---

graph/api/src/main/java/org/jboss/windup/graph/model/ProjectModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/tests/pom.xml
reporting/tests/src/test/java/org/jboss/windup/reporting/CSVExportingTest.java

https://issues.jboss.org/browse/WINDUP-1459

WINDUP-1459: Create a link from the application list to the CSV report (if available). This allows access from the web ui as well

---

reporting/impl/src/main/resources/reports/resources/css/tech-report-punchcard.css

Fixing various style issues: character encoding, alignment, colors.

Fixing various style issues: character encoding, alignment, colors.

---

rules-java/api/src/main/resources/reports/templates/java_application.ftl

https://issues.jboss.org/browse/WINDUP-1958

WINDUP-1958: Tech Reports: 'Technology' ambiguous

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/tests/src/test/resources/test-exports/app1.csv
reporting/tests/src/test/resources/test-exports/app2.csv
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSourceModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java

https://issues.jboss.org/browse/WINDUP-1991

WINDUP-1991: Switched issue type to issue category and added a test

---

graph/api/src/main/java/org/jboss/windup/graph/service/GraphService.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/decompiler/AbstractDecompilerOperation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/AnalyzeJavaFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/AddArchiveReferenceInformation.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/RecurseDirectoryAndAddFiles.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/UnzipArchiveToOutputFolder.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverPropertiesFilesRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/service/WindupJavaConfigurationService.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/ignore/JavaIgnoreRegexesTest.java

https://issues.jboss.org/browse/WINDUP-1327
(just in progress... code should work, but it needs tests)

Windup 1327

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js

Now  Tags filter works like Name filter.
https://issues.jboss.org/browse/WINDUP-1956

WINDUP-1956 Tags filter like Name filter

---

config/api/src/main/java/org/jboss/windup/config/builder/RuleProviderBuilder.java
config/api/src/main/java/org/jboss/windup/config/builder/RuleProviderBuilderMetadataAddSourceTechnology.java
config/api/src/main/java/org/jboss/windup/config/builder/RuleProviderBuilderMetadataAddTargetTechnology.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/model/AbstractJavaSourceModel.java

Related PR: https://github.com/windup/windup-rulesets/pull/327

WINDUPRULE-331: Useful method for the rules PR -- allows more easily searching all type references

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/DiscoverPackagesCommand.java

https://issues.jboss.org/browse/WINDUP-852

WINDUP-852: Better validation for the input path in --discoverPackages

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js
reporting/impl/src/main/resources/reports/templates/include/filtering_bar.ftl

This should fix the problem Marco found yesterday

WINDUP-1957: make error display bar reusable

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/addons/InstallAddonCommand.java
bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/addons/RemoveAddonCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/InstallRemoveAddonCommandsTest.java

https://issues.jboss.org/browse/WINDUP-843

WINDUP-843: The help description of --install and --remove is incorrect

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js
test-util/src/main/java/org/jboss/windup/testutil/html/TestApplicationListUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupMultiAppBasicTest.java

https://issues.jboss.org/browse/WINDUP-2015

WINDUP-2015: Fixed application list sorting when there are greater than 1,000 story points

---

exec/api/src/main/java/org/jboss/windup/exec/configuration/options/OutputPathOption.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/MissingJavaArchivesInInputPathTest.java

https://issues.jboss.org/browse/WINDUP-2042

WINDUP-2042 Fix input path with no Java archives

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js
test-util/src/main/java/org/jboss/windup/testutil/html/TestApplicationListUtil.java
tests/src/test/groovy/GroovyExampleRule.windup.groovy
tests/src/test/java/org/jboss/windup/tests/application/WindupMultiAppBasicTest.java

https://issues.jboss.org/browse/WINDUP-2035

WINDUP-2035: Application list: tag filter is not working as expected

---

utils/src/main/java/org/jboss/windup/util/file/FileVisit.java

Little change for https://github.com/windup/windup-rulesets/pull/334

WIP WINDUP-2000 Create Validation report

---

graph/api/src/main/java/org/jboss/windup/graph/model/resource/FileModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/techreport/IsFileADirectoryMethod.java
reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/operation/RecurseDirectoryAndAddFiles.java

https://issues.jboss.org/browse/WINDUP-2056

WINDUP-2056: size not calculated for directories in Tech report

---

exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/InputApplicationName.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
graph/api/src/main/java/org/jboss/windup/graph/service/ProjectService.java
reporting/impl/src/main/resources/reports/templates/application_list.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
reporting/impl/src/main/resources/reports/templates/techReport-boxes.ftl
reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
rules-java-ee/addon/src/main/resources/reports/templates/hibernate.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jbpm.ftl
rules-java-ee/addon/src/main/resources/reports/templates/jpa.ftl
rules-java-ee/addon/src/main/resources/reports/templates/remote.ftl
rules-java-ee/addon/src/main/resources/reports/templates/server.ftl
rules-java-ee/addon/src/main/resources/reports/templates/spring.ftl
rules-java/api/src/main/resources/reports/templates/compatible_files.ftl
rules-java/api/src/main/resources/reports/templates/dependency_report.ftl
rules-java/api/src/main/resources/reports/templates/hardcoded_ip_addresses.ftl
rules-java/api/src/main/resources/reports/templates/ignored_files.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl
rules-java/api/src/main/resources/reports/templates/report_index.ftl
rules-java/api/src/main/resources/reports/templates/unparsable_files.ftl

https://issues.jboss.org/browse/WINDUP-1987

WINDUP-1987: Allow the specification of the application name(s) by parameter

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationTest.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/DiscoverEjbConfigurationTest.java
rules-java-ee/tests/src/test/resources/ejb/entity/EJB2EntityNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/mdb/EJBMessageDrivenNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/session/EJB2RemoteInterfaceNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/session/EJB2SessionBeanNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/session/EJB2SessionHomeNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/session/EJBLocalHomeNotInEJBXML.java
rules-java-ee/tests/src/test/resources/ejb/session/EJBLocalObjectNotInEJBXML.java

https://issues.jboss.org/browse/WINDUP-758

WINDUP-758: Fixed missing detection of some beans

---

reporting/impl/src/main/resources/reports/resources/css/tech-report-punchcard.css
reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl

https://issues.jboss.org/browse/WINDUP-1977

WINDUP-1977: Added name header and made the report sorted by name by default

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/resources/reports/templates/ejb.ftl
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureJEEExampleTest.java

https://issues.jboss.org/browse/WINDUP-758

WINDUP-758: Fixed reporting to list home interfaces

---

reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/techreport/CreateTechReportRuleProvider.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/techreport/TechReportService.java
reporting/impl/src/main/resources/reports/resources/css/tech-report-punchcard.css
reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl

tooltip boxes on technology punchcard report not resizing to show full width of text contents.
https://issues.jboss.org/browse/WINDUP-2177

WINDUP-2177: Enrich mouse over information on tech punch card

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/ApplicationReportModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
reporting/impl/src/main/java/org/jboss/windup/reporting/rules/generation/CreateMigrationIssuesReportRuleProvider.java
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl

There's another JIRA for providing a link in the web-ui to the file produced.
To check the file produced independently of that you need to navigate to where the reports for the analysis are stored in the file system.

WINDUP-2026: produce csv report of all applications' results merged

---

bom/pom.xml
config/impl/pom.xml
config/impl/src/main/java/org/jboss/windup/config/loader/RuleProviderSorter.java
decompiler/impl-procyon/pom.xml
decompiler/impl-procyon/src/main/java/com/strobel/assembler/metadata/NoRetryMetadataSystem.java
decompiler/impl-procyon/src/main/java/com/strobel/assembler/metadata/WindupClasspathTypeLoader.java
decompiler/impl-procyon/src/main/java/com/strobel/assembler/metadata/WindupMetadataSystem.java
decompiler/impl-procyon/src/main/java/org/jboss/windup/decompiler/procyon/ProcyonDecompiler.java
forks/jdt/pom.xml
forks/jdt/src/main/java/org/eclipse/jdt/internal/compiler/Compiler.java
graph/api/pom.xml
java-ast/addon/pom.xml
java-ast/addon/src/main/java/org/jboss/windup/ast/java/ASTProcessor.java
java-ast/addon/src/main/java/org/jboss/windup/ast/java/BatchASTProcessor.java
pom.xml
test-util/src/main/java/org/jboss/windup/testutil/html/TestApplicationListUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestChromeDriverReportUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestCompatibleReportUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestDependencyGraphReportUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestHardcodedPReportUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestJavaApplicationOverviewUtil.java
test-util/src/main/java/org/jboss/windup/testutil/html/TestReportIndexReportUtil.java
tests/pom.xml
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeFernflowerTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeProcyonTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeTest.java
tooling/api/pom.xml
utils/src/main/java/org/jboss/windup/util/xml/XmlUtil.java

PR with all of the WIP changes to test the latest updates needed to run RHAMT on JDK 11.
The basic idea is to have the changes that let us have a working build for the CLI.

WINDUP-2171 JDK 11 compatibility - CLI

---

reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml
reporting/tests/src/test/java/org/jboss/windup/reporting/rules/generation/techreport/TechReportServiceTest.java

In order to show EJB box in Technology Report we need to add the existing techBox:ejb as placeBox
[Jira Ticket]( https://issues.jboss.org/browse/WINDUP-2353)

Windup 2353 : added new EJB placebox

---

reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml

NB: this pr works in conjunction with https://github.com/windup/windup-rulesets/pull/371

WINDUP-2337: tech report jax-rs moved from http to rest category

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/migrate/ExportCsvTest.java

This handles the production of the new file which can be found in the report folder.

WINDUP-2351: exportCSV new file with tags listed by application

---

bom/pom.xml

https://issues.jboss.org/browse/WINDUP-2460

WINDUP-2460 Bump nexus-indexer-data version

---

bom/pom.xml

https://issues.jboss.org/browse/WINDUP-2485

WINDUP-2485 Bump nexus-indexer-data version

---

reporting/impl/src/main/resources/reports/resources/js/windup-application-list-sorting.js
test-util/src/main/java/org/jboss/windup/testutil/html/TestApplicationListUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureJEEExampleTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureTest.java
tests/src/test/xml/rules/test.windup.label.xml

https://issues.jboss.org/browse/WINDUP-2492
Legend:
- Add neutral tags
- Sort tags

WINDUP-2492: Application List Report - Technology Tags

---

reporting/impl/src/main/resources/reports/templates/application_list.ftl
test-util/src/main/java/org/jboss/windup/testutil/html/TestApplicationListUtil.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureJEEExampleTest.java

Added the neutral label to the legend:

Target Runtime Labels Legend: add neutral label

---

reporting/impl/src/main/resources/reports/templates/techReport-punchCard.ftl

https://issues.redhat.com/browse/WINDUP-2372

WINDUP-2372: bubble report sectorStats column sorting not working

---

rules-java-project/addon/src/main/java/org/jboss/windup/project/condition/Project.java
rules-java-project/tests/src/test/java/org/jboss/windup/project/operation/test/ProjectWithHintTest.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/Dependency.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/DependencyTest.java

https://issues.redhat.com/browse/WINDUP-2525
PR with code to have ~~https://github.com/windup/windup-rulesets/pull/390~~ https://github.com/windup/windup-rulesets/pull/397 to work.

WINDUP-2525 <where> parameter in <artifact> condition doesn't work

---

bom/pom.xml
pom.xml

https://issues.redhat.com/browse/WINDUP-2510

WINDUP-2510 Bump Furnace version to 2.28.4.Final

---

tooling/impl/pom.xml
tooling/impl/src/main/java/org/jboss/windup/tooling/ExecutionBuilderImpl.java
tooling/tests/src/test/java/org/jboss/windup/tooling/ToolingModeTest.java

https://issues.redhat.com/browse/WINDUP-2658
- added Java XML dependencies removed in JDK 11
- removed unused import and instances in classes

WINDUP-2658 Added Java XML dependencies

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUPRULE-662

WINDUPRULE-662 Bump Maven Lucene index version

---

graph/api/src/main/java/org/jboss/windup/graph/service/FileLocationService.java
rules-java-project/addon/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/Dependency.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/DependencyTest.java

https://issues.redhat.com/browse/WINDUPRULE-667

WINDUPRULE-667 Fixed dependency found to be unique

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-2765

WINDUP-2765 Bump Index version

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/tests/src/test/resources/NonNamespacedMavenDiscoveryTest/pom.xml

https://issues.redhat.com/browse/WINDUP-2771

WINDUP-2771 Excluded optional dependencies from analysis

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-2936

WINDUP-2936 Bump Maven index version

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/ip/DiscoverHardcodedIPAddressRuleProvider.java

https://issues.redhat.com/browse/WINDUPRULE-697

WINDUPRULE-697 Added 'cloud-readiness' target to DiscoverHardcodedIPAddressRuleProvider rule

---

config-groovy/addon/pom.xml

https://issues.redhat.com/browse/WINDUP-2937

WINDUP-2937 Bump Groovy artifact version

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-2949

WINDUP-2949 Bump Maven index version to 21.01.14.Final

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-2988

WINDUP-2988 Bump Maven Index version

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-3027

WINDUP-3027 Bump Maven Index version

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-3047

WINDUP-3047 Bump Maven Index version

---

forks/jdt/pom.xml
java-ast/addon/pom.xml

https://issues.redhat.com/browse/WINDUP-3112

Fixed Eclipse deps' versions

---

bom/pom.xml
forks/jdt/pom.xml
graph/api/src/main/java/org/jboss/windup/graph/GraphModelScanner.java

https://issues.redhat.com/browse/WINDUP-3112
Fixes for restoring the Windup Web Console builds.

WINDUP-3112 Fixes for building and running the Web Console

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-3114

WINDUP-3114 Bump Maven Index version

---

.github/workflows/pull_request.yml

https://issues.redhat.com/browse/WINDUP-3142

WINDUP-3142 Initial and basic GH Worflow for new build on JDK 11

---

bom/pom.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3185).

[WINDUP-3185] Upgrade nexus index to latest version

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/scan/provider/MavenElementValueResolverTest.java
rules-java/tests/src/test/resources/org/jboss/windup/rules/java/pom-property-with-multiple-variables.xml

Also refactored to extract a testable utility class, avoiding the need of creating another integration test.
See Jira ticket [WINDUP-3231](https://issues.redhat.com/browse/WINDUP-3231).

[WINDUP-3231] Enhance to accept more complex maven element values' expressions

---

rules-java/api/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/condition/Version.java
rules-java/tests/src/test/java/org/jboss/windup/rules/java/VersionTest.java

Fixes the version comparison algorithm. See [WINDUP-3233](https://issues.redhat.com/browse/WINDUP-3233).

[WINDUP-3233] Fix version parsing

---

.github/workflows/pr_build_jdk11.yml
.github/workflows/pr_build_jdk11_dependents.yml
pom.xml
test-util/pom.xml
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureMediumBinaryModeProcyonTest.java

See [this list of default variables present in workflow images](https://github.com/actions/virtual-environments/blob/ffa2110464ecda1cc62b477f29609525de24e570/images/linux/Ubuntu1804-README.md).

[WINDUP-3215] Specify chrome driver location

---

.github/workflows/pr_build_jdk11_dependents.yml

See [WINDUP-3215](https://issues.redhat.com/browse/WINDUP-3215)

[WINDUP-3215] Set all jobs to use ubuntu-latest

---

bootstrap/pom.xml

See [WINDUP-3213](https://issues.redhat.com/browse/WINDUP-3213).

[WINDUP-3213] Upgrade dom4j dependency

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/OverviewReportLineMessageModel.java

https://issues.redhat.com/browse/WINDUP-3307

WINDUP-3307 Avoid 'project' value collision in the graph

---

bom/pom.xml
rules-java-archives/addon/src/test/java/org/jboss/windup/rules/apps/java/archives/identify/test/LuceneFileArchiveIdentificationServiceTest.java

https://issues.redhat.com/browse/WINDUP-3308

WINDUP-3308 Bump Lucene index version 22.03.16.Final

---

config/impl/src/main/java/org/jboss/windup/config/metadata/RuleProviderRegistryCacheImpl.java
exec/tests/src/test/java/org/jboss/windup/exec/configuration/MetadataOptionsTest.java

https://issues.redhat.com/browse/WINDUP-3329

WINDUP-3329 MTA CLI source and target sorted

---

graph/api/src/main/resources/META-INF/services/org.jboss.forge.furnace.container.simple.SingletonService

GraphTypeRegistry has been refactored in https://github.com/windup/windup/pull/754

GraphTypeRegistry has been refactored in https://github.com/windup/windup/pull/754

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3313).

[WINDUP-3313] Fix pluginManagement XPath

---

rules-java/api/src/main/resources/reports/resources/js/windup-overview.js

https://issues.redhat.com/browse/WINDUP-3390
Note: This application can be used for testing the change https://github.com/windup/windup-sample-apps/blob/master/sample-binaries/jee-example-app-1.0.0.ear

[WINDUP-3390]-Application Details Report - formatting issue

---

pom.xml

https://issues.redhat.com/browse/WINDUP-3401

[WINDUP-3401]-upgrade jackson-databind

---

.github/workflows/pr_build_jdk11_dependents.yml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/provider/DiscoverMavenProjectsRuleProvider.java

https://issues.redhat.com/browse/WINDUP-3412

[WINDUP-3412]-Windup CLI: TransformerException: JAXP0801002: the compiler encountered an XPath expression containing '101' operators

---

pom.xml
rules-yaml/addon/pom.xml
rules-yaml/addon/src/main/resources/META-INF/beans.xml
rules-yaml/api/pom.xml
rules-yaml/api/src/main/java/org/jboss/windup/rules/apps/yaml/DiscoverYamlFilesRuleProvider.java
rules-yaml/api/src/main/java/org/jboss/windup/rules/apps/yaml/YamlSourceTypeResolver.java
rules-yaml/api/src/main/java/org/jboss/windup/rules/apps/yaml/model/YamlFileModel.java
rules-yaml/api/src/main/resources/META-INF/beans.xml
rules-yaml/api/src/test/java/org/jboss/windup/rules/apps/yaml/DiscoverYamlFilesRuleProviderTest.java
rules-yaml/api/src/test/resources/yaml-files/props.yaml
rules-yaml/pom.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3419).

[WINDUP-3419] Enable being able to explore yaml files in reports using filecontent rule

---

pom.xml

https://issues.redhat.com/browse/WINDUP-3461

[WINDUP-3461] - The MTR Themes should point to correct links

---

README.asciidoc

[WINDUP-3409](https://issues.redhat.com/browse/WINDUP-3409)

README changes  

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/ToolingModeCommand.java
tests/src/test/java/org/jboss/windup/tests/bootstrap/ToolingModeCommandTest.java
tooling/api/src/main/java/org/jboss/windup/tooling/IOptionKeys.java

Signed-off-by: John Steele <programjsteele@gmail.com>

add Diva (enableTransactionAnalysis) support to tooling

---

exec/api/pom.xml
pom.xml
windup-test-harness/pom.xml

https://issues.redhat.com/browse/WINDUP-3502

Bump org.apache.maven.shared:maven-shared-utils:3.3.4

---

bootstraps-themed/pom.xml

To reproduce the issue, build a CLI on latest `master` branch and run it in "tooling mode" executing the command:
```
./windup-cli --input <input_path> --sourceMode --target azure-aks --output <output_path> --toolingMode --windupHome <path_to_CLI_bin_folder>
```
and you should get:
```
WINDUP execution failed due to: org/jboss/windup/tooling/ToolingModeRunner
java.lang.NoClassDefFoundError: org/jboss/windup/tooling/ToolingModeRunner
at org.jboss.windup.bootstrap.commands.windup.ToolingModeCommand.analyze(ToolingModeCommand.java:121)
at org.jboss.windup.bootstrap.commands.windup.ToolingModeCommand.execute(ToolingModeCommand.java:60)
at org.jboss.windup.bootstrap.Bootstrap.toolingMode(Bootstrap.java:448)
at org.jboss.windup.bootstrap.Bootstrap.main(Bootstrap.java:107)
Caused by: …
```

Added the 'windup-tooling-api' artifact to bootstrap

---

rules-java/api/pom.xml

https://issues.redhat.com/browse/WINDUP-3550

WINDUP-3550 Bump BCEL 6.6.1

---

rules-java/api/pom.xml

backport #1559 
https://issues.redhat.com/browse/WINDUP-3550

WINDUP-3550 Bump BCEL 6.6.1 (#1559)

---

pom.xml

backports https://github.com/windup/windup/pull/1568

Bump jackson-databind 2.13.4.2 (#1568)

---

bom/pom.xml

Bump Nexus index 22.11.28.Final

---

reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml
rules-java/api/src/main/resources/data/java-ee.tags.xml

https://issues.redhat.com/browse/WINDUP-3559

[WINDUP-3559] - Technology Reports - replace Java EE with Jakarta EE

---

bom/pom.xml

Bump Nexus index 22.12.14.Final

---

reporting/impl/src/main/resources/org/jboss/windup/reporting/rules/generation/techreport/techReport-hierarchy.tags.xml
rules-java/api/src/main/resources/data/java-ee.tags.xml

https://issues.redhat.com/browse/WINDUP-3559
Original PR is at https://github.com/windup/windup/pull/1571

[WINDUP-3559] - backport - Technology Reports - replace Java EE with Jakarta EE 

---

bom/pom.xml
config/impl/src/main/java/org/jboss/windup/config/loader/RuleLoaderImpl.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologiesIntersector.java
reporting/api/src/main/java/org/jboss/windup/reporting/config/classification/Classification.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetIssueCategoriesMethod.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/GetSourcesAndTargetsMethod.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/ProblemSummary.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/ProblemSummaryService.java
reporting/api/src/main/java/org/jboss/windup/reporting/freemarker/problemsummary/SourcesAndTargets.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/ClassificationModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/InlineHintModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/model/SourcesAndTargetsModel.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/InlineHintService.java
reporting/impl/src/main/resources/reports/resources/css/windup.css
reporting/impl/src/main/resources/reports/resources/js/windup-issues-filtering.js
reporting/impl/src/main/resources/reports/templates/include/problem_summary.ftl
reporting/impl/src/main/resources/reports/templates/include/sources_targets.ftl
reporting/impl/src/main/resources/reports/templates/migration-issues.ftl
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java

See [JIRA ticket](https://issues.redhat.com/browse/WINDUP-3410).

[WINDUP-3410] Add source and target info to each hint

---

reporting/api/src/main/java/org/jboss/windup/reporting/model/DefaultTechnologyTagComparator.java
reporting/api/src/main/java/org/jboss/windup/reporting/service/TechnologyTagService.java
reporting/tests/src/test/java/org/jboss/windup/reporting/service/TechnologyTagServiceTest.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverEjbConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJpaConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverWebXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/jboss/jbpm3/DiscoverJBossJbpmProcessFilesRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/orion/ResolveOrionWebXmlRuleProvider.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/EjbXmlParsingTest.java
tests/src/test/java/org/jboss/windup/tests/application/WindupArchitectureSeamBookingSourceTest.java
utils/pom.xml

backport https://github.com/windup/windup/pull/1587

WINDUP-3663 Fixed some Java EE tech tag version management (#1587)

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJpaConfigurationXmlRuleProvider.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/util/HibernateDialectDataSourceTypeResolver.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/rules/DiscoverJpaConfigurationXmlRuleProviderTest.java
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-1.0.xml
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-2.0.xml
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-2.1.xml
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-2.2.xml
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-3.0.xml
rules-java-ee/tests/src/test/resources/jpa/xml/persistence-3.1.xml

https://issues.redhat.com/browse/WINDUP-3668
- added required namespaces
- created `DiscoverJpaConfigurationXmlRuleProviderTest` test with 6 sample files (thanks to https://github.com/windup/windup-rulesets/pull/846 from @agoncal)

WINDUP-3668 Enhanced DiscoverJpaConfigurationXmlRuleProvider and created test

---

pom.xml

backport https://github.com/windup/windup/pull/1593

Set manual dependency (#1593)

---

exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/options/ExportSummaryOption.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
graph/api/src/main/java/org/jboss/windup/graph/model/WindupConfigurationModel.java
reporting/impl/pom.xml
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProviderTest.java
rules-java/tests/src/test/resources/issueSummary/app1/HelloWorld.java
rules-java/tests/src/test/resources/issueSummary/app2/HelloWorld.java

WINDUP-3370 export summary file

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/XMLTechnologyReferenceAliasTranslatorLoader.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
exec/tests/pom.xml
exec/tests/src/test/java/org/jboss/windup/exec/test/TechnologyReferenceTransformersTest.java
exec/tests/src/test/resources/sample.windup.technologytransformer.xml

https://issues.redhat.com/browse/WINDUP-3715

WINDUP-3715 Enabled multiple transformations for a single source/target input value

---

config-xml/addon/src/main/java/org/jboss/windup/config/parser/XMLTechnologyReferenceAliasTranslatorLoader.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
exec/tests/pom.xml
exec/tests/src/test/java/org/jboss/windup/exec/test/TechnologyReferenceTransformersTest.java
exec/tests/src/test/resources/sample.windup.technologytransformer.xml

backport #1604 
https://issues.redhat.com/browse/WINDUP-3715

[releases/6.1.z] WINDUP-3715 Enabled multiple transformations for a single source/target input value 

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProvider.java
rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateJsonSummaryRuleProvider.java
rules-java/tests/src/test/java/org/jboss/windup/rules/apps/java/reporting/rules/CreateIssueSummaryDataRuleProviderTest.java

backport #1606 
https://issues.redhat.com/browse/WINDUP-3720

[releases/6.1.z] WINDUP-3720 Decoupled JSON extract generation from reports rendering

---

rules-java/api/src/main/resources/reports/templates/dependency_report.ftl
rules-java/api/src/main/resources/reports/templates/java_application.ftl

https://issues.redhat.com/browse/WINDUP-3722

WINDUP-3722 Added param to use 'search.maven.org' website

---

rules-java/api/src/main/java/org/jboss/windup/rules/apps/java/scan/ast/AnalyzeJavaFilesRuleProvider.java

This PR will allow having `annotation-type` subconditions inside of `javaclass` conditions for `locations` where elements can be annotated, ie: class declarations, fields and methods.
See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3725).

[WINDUP-3725] Fix annotated-type condition on javaclass other than location=ANNOTATION

---

bom/pom.xml
test-util/pom.xml
test-util/src/main/java/org/jboss/windup/testutil/html/TestChromeDriverReportUtil.java

New build of nexus-repository-indexer project released, `23.03.15.Final`

new nexus-indexer version

---

test-util/pom.xml
test-util/src/main/java/org/jboss/windup/testutil/html/TestChromeDriverReportUtil.java

[releases/6.1.z] Fix 'windup-tests' job

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java
exec/api/src/main/java/org/jboss/windup/exec/Util.java

https://issues.redhat.com/browse/WINDUP-3748

WINDUP-3748 Refactored 'deleteGraphDataUnlessInhibited' method

---

.github/workflows/pr_build_jdk11.yml
.github/workflows/pr_build_jdk11_dependents.yml
pom.xml
tests/pom.xml

https://issues.redhat.com/browse/WINDUP-3602
depends on
- https://github.com/windup/windup-rulesets/pull/893
- https://github.com/windup/windup-maven-plugin/pull/43
- https://github.com/windup/windup-quickstarts/pull/112

WINDUP-3602 Run project's tests on JDK 11 and 17

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/TechnologiesIntersector.java
reporting/tests/src/test/java/org/jboss/windup/reporting/config/TechnologiesIntersectorTest.java

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3726).

[WINDUP-3726] Fix tech intersection

---

config/api/src/main/java/org/jboss/windup/config/ExportZipOutputOption.java
exec/api/src/main/java/org/jboss/windup/exec/configuration/WindupConfiguration.java
exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
graph/api/src/main/java/org/jboss/windup/graph/model/WindupConfigurationModel.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportZipReportRuleProvider.java
reporting/tests/src/test/java/org/jboss/windup/reporting/ZipExportingTest.java
utils/src/main/java/org/jboss/windup/util/ZipUtil.java

https://issues.redhat.com/browse/WINDUP-3721

WINDUP-3721 Add '--exportZipReport' input option

---

reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportCSVFileRuleProvider.java

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3767).
Prevents the CSV generator from trying to generate a record out of a rule file. This rule file is leaking somewhere into the input for some reason (I haven't been able to find where or why).

[WINDUP-3767] Check for user rule files leaking as input

---

pf-ui/pom.xml

Node and NPM versions taken from https://nodejs.org/en/download/releases

Bump Node v16.20.0 - NPM 8.19.4

---

exec/impl/src/main/java/org/jboss/windup/exec/WindupProcessorImpl.java
reporting/impl/src/main/java/org/jboss/windup/reporting/export/ExportZipReportRuleProvider.java

https://issues.redhat.com/browse/WINDUP-3793

WINDUP-3793 ZIP creation: add 'logs' folder to excluded prefixes list

---

pf-ui/src/main/webapp/src/pages/application-edit/pages/details/components/application-files-table.tsx

https://issues.redhat.com/browse/WINDUP-3805

WINDUP-3805 'Collapse all' typo

---

rules-java/api/pom.xml
rules-java/tests/src/test/java/org/jboss/windup/rules/java/VersionTest.java

https://issues.redhat.com/browse/WINDUP-3812

WINDUP-3812 Bump maven-artifact 3.9.1

---

bootstrap/src/main/java/org/jboss/windup/bootstrap/commands/windup/RunWindupCommand.java

https://issues.redhat.com/browse/MTA-458

MTA-458 Enhanced the input values management

---

pf-ui/src/main/webapp/src/shared/components/issues-table/components/issue-overview.tsx

https://issues.redhat.com/browse/WINDUP-3809

[WINDUP-3809] - Improper alignment in case of file without references to source code.

---

pf-ui/src/main/webapp/src/shared/components/rule-editor/rule-editor.tsx

https://issues.redhat.com/browse/WINDUP-3813

[WINDUP-3813] - "View rule" with Java rule has broken syntax highlighting

---

pf-ui/src/main/webapp/src/pages/application-edit/pages/details/components/application-files-children-table.tsx

https://issues.redhat.com/browse/WINDUP-3839

[WINDUP-3839] - New reports: issues reported twice in "Details" file

---

pf-ui/src/main/webapp/src/api/rule.ts
pf-ui/src/main/webapp/src/pages/rules-list/rules-list.tsx
pf-ui/src/main/webapp/src/queries/mocks/rules.mock.ts
reporting-data/addon/src/main/java/org/jboss/windup/reporting/data/dto/RuleDto.java
reporting-data/addon/src/main/java/org/jboss/windup/reporting/data/rules/RulesRuleProvider.java

https://issues.redhat.com/browse/WINDUP-3840

[WINDUP-3840] - New reports: Rules report is missing the ruleset ID

---

pf-ui/src/main/webapp/src/shared/components/issues-table/components/issue-overview.tsx
pf-ui/src/main/webapp/src/shared/components/issues-table/issues-table.tsx

https://issues.redhat.com/browse/WINDUP-3842

[WINDUP-3842] - Source code window not in sync with the Issues reported

---

reporting/api/src/main/java/org/jboss/windup/reporting/config/Hint.java

It can happen that some (supposed to be) parameters in hint's title and body have no values and this situation has been fully managed so far printing a warning followed by the exception's stacktrace.
It happened that some rules, perfectly working, managed to trigger this situation a lot of stacktraces were printed on the log for basically no reason considering the warning message already clarifies what happened.
So I've remove the stacktrace logging to avoid misunderstanding about this not being managed.
Then, since the same hint will generate the same log multiple times, I've managed to print it just once per hint (i.e. per rule) with the same approach to logging adopted also in other situation in Windup.

Hint: removed stacktrace printing for some warnings

---

rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyUsageStatisticsModelExists.java
rules-java-ee/addon/src/main/java/org/jboss/windup/rules/apps/javaee/TechnologyUsageStatisticsService.java
rules-java-ee/tests/src/test/java/org/jboss/windup/rules/apps/javaee/tests/TechnologyIdentifiedTest.java

https://issues.redhat.com/browse/WINDUPRULE-985
Follows ups https://issues.redhat.com/browse/WINDUPRULE-978
It fixes `technology-usage-web-01400-test` test [failure](https://github.com/windup/windup-rulesets/actions/runs/4892236387/jobs/8733920657?pr=939) in https://github.com/windup/windup-rulesets/pull/939

WINDUPRULE-985 Rules testing: technology-statistics-exists has inconsistent number-found

---

pom.xml
rules-java-archives/addon/pom.xml
ui/addon/pom.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3787).

[WINDUP-3787] Remove unneeded dependency

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-3879

[WINDUP-3879] - New PF4 Reports - Source Code Report not active with yaml files

---

java-ast/addon/src/main/java/org/jboss/windup/ast/java/ASTProcessor.java
rules-java/api/pom.xml
rules-yaml/api/pom.xml

See [Jira ticket](https://issues.redhat.com/browse/WINDUP-3937).
See the [ASM versions document](https://asm.ow2.io/versions.html) for more info on the dependency bump.

[WINDUP-3937] Add ability to decompile and analyse Java 17 apps

---

bom/pom.xml

See [WINDUP-3949](https://issues.redhat.com/browse/WINDUP-3949).

[WINDUP-3949] Bump guava version

---

bom/pom.xml
pom.xml

https://issues.sonatype.org/browse/OSSRH-96863

Update Sonatype repository

---

pom.xml

upgrade jackson-databind version 
https://issues.redhat.com/browse/WINDUP-3926

WINDUP-3926

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

https://issues.redhat.com/browse/WINDUP-4117

[WINDUP-4117] - Upgrade follow-redirect

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

https://issues.redhat.com/browse/WINDUP-3958

[WINDUP-3958] - Upgrade tough-cookie

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

https://issues.redhat.com/browse/WINDUP-3963

[WINDUP-3963] - Upgrade semver

---

graph/api/pom.xml

https://issues.redhat.com/browse/WINDUP-4028

WINDUP-4028 upgrade ivy version

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-4155

WINDUP-4155: upgrade commons-configuration 2 to v2.10.1

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

https://issues.redhat.com/browse/WINDUP-4115
https://issues.redhat.com/browse/WINDUP-4098
https://bugzilla.redhat.com/show_bug.cgi?id=2254559

WINDUP-4115 CVE upgrade css-tools

---

pf-ui/src/main/webapp/package-lock.json
pf-ui/src/main/webapp/package.json

https://issues.redhat.com/browse/WINDUP-4156

WINDUP-4156 CVE upgrade webpack-dev-middleware

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-4049

WINDUP-4049 CVE update jetty

---

bom/pom.xml

https://issues.redhat.com/browse/WINDUP-4158

WINDUP-4158: netty-codec-http cve fix

---

config-xml/addon/pom.xml
reporting/impl/pom.xml
rules-java-ee/addon/pom.xml
rules-java-project/addon/pom.xml
rules-xml/impl/pom.xml

updated org.jooq joox dependency to version 1.6.2

WINDUP-4219 update joox dependency
